export default [
  {
    speaker: '小云',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'xiaoyun',
    speechType: '标准女声',
    scene: '通用场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: 'lite版',
    speechFrom: '官方',
    text: '广袤的辽北大地，处处萌发盎然春意。'
  },
  {
    speaker: '小刚',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'xiaogang',
    speechType: '标准男声',
    scene: '通用场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: 'lite版',
    speechFrom: '官方',
    text: '当天，北京飞往上海虹桥的航班也因天气原因导致延误。'
  },
  {
    speaker: '若兮',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'ruoxi',
    speechType: '温柔女声',
    scene: '通用场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '这一次交锋，双方都没有占到什么便宜，可以说是旗鼓相当。'
  },
  {
    speaker: '思琪',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'siqi',
    speechType: '温柔女声',
    scene: '通用场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '有人说，他性格外冷内热，更多的人认为他冷酷无情。'
  },
  {
    speaker: '思佳',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'sijia',
    speechType: '标准女声',
    scene: '通用场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '尽管已年近七旬，但王时凯看起来依然精神矍铄。'
  },
  {
    speaker: '思诚',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'sicheng',
    speechType: '标准男声',
    scene: '通用场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '在全市形成了上下联动、共同推进的良好氛围。'
  },
  {
    speaker: '艾琪',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'aiqi',
    speechType: '温柔女声',
    scene: '通用场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '哎呀，你要问我喜欢吃什么，我能答上一堆。问我不喜欢的啊，那我还真答不上来。'
  },
  {
    speaker: '艾佳',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'aijia',
    speechType: '标准女声',
    scene: '通用场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '从目前来看，创业板显然并未受到严重的影响。'
  },
  {
    speaker: '艾诚',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'aicheng',
    speechType: '标准男声',
    scene: '通用场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '信息革命、移动互联网革命尚未落幕，智能革命又像一头大象一样撞进人类的生活，激荡着整个世界。'
  },
  {
    speaker: '艾达',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'aida',
    speechType: '标准男声',
    scene: '通用场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '乡村是中国的根脉，是国家大厦的基础，乡村治理具有极端重要性。'
  },
  {
    speaker: '宁儿',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'ninger',
    speechType: '标准女声',
    scene: '通用场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '随着量能的放大、涨停股的增多，市场被调动起来。'
  },
  {
    speaker: '瑞琳',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'ruilin',
    speechType: '标准女声',
    scene: '通用场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '中国传统文化讲究节日团圆，到了春节，就更期待一家人聚在一起热热闹闹的吃饭啦。'
  },
  {
    speaker: '思悦',
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    speakerId: 'siyue',
    speechType: '温柔女声',
    scene: '客服场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '张先生您好，您本月VPN流量已使用百分之八十，您还可以查询四月及近五个月的账单。'
  },
  {
    speaker: '艾雅',
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    speakerId: 'aiya',
    speechType: '严厉女声',
    scene: '客服场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '是这样子的，张欢女士，现在您的信用卡，因为逾期31天以上，已经被冻结停卡。'
  },
  {
    speaker: '艾夏',
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    speakerId: 'aixia',
    speechType: '亲和女声',
    scene: '客服场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '为了减少您的损失，请您今天晚上6点前尽快处理好本次欠款，好吧？'
  },
  {
    speaker: '艾美',
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    speakerId: 'aimei',
    speechType: '甜美女声',
    scene: '客服场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '您好，我这边是XY证券的，您开户的证券公司，请问是李万峰先生吗？想和您做个简单的回访，可以吗？'
  },
  {
    speaker: '艾雨',
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    speakerId: 'aiyu',
    speechType: '自然女声',
    scene: '客服场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '这项手机保障权益只针对新购买1个月内的手机有效，置换费需要125元。'
  },
  {
    speaker: '艾悦',
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    speakerId: 'aiyue',
    speechType: '温柔女声',
    scene: '客服场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '好的，王先生，最后温馨提醒您，我银行将在您申请财智金成功批核后，为您发送《财智金产品服务协议》及资金用途管控要求的短信，请您注意查阅。那先不打扰您了，祝您用卡愉快，谢谢您的接听，再见。'
  },
  {
    speaker: '艾婧',
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    speakerId: 'aijing',
    speechType: '严厉女声',
    scene: '客服场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '如果您在今天下午六点之前仍未进行处理，将会产生更多不必要的费用，并且会影响您的信用记录。'
  },
  {
    speaker: '小美',
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    speakerId: 'xiaomei',
    speechType: '甜美女声',
    scene: '客服场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '齐先生，您的支付宝绑定的是18912345678这个手机号吗？'
  },
  {
    speaker: '艾娜',
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    speakerId: 'aina',
    speechType: '浙普女声',
    scene: '客服场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '现在需要和您确认，当前接听的这部手机是否是在1个月内购买的。'
  },
  {
    speaker: '伊娜',
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    speakerId: 'yina',
    speechType: '浙普女声',
    scene: '客服场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '尊敬的王大志先生，我是智能数码专营店的售后客服，请问有什么可以帮您？'
  },
  {
    speaker: '思婧',
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    speakerId: 'sijing',
    speechType: '严厉女声',
    scene: '客服场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '您的欠款98789.1元，在5月1号即将到还款日期，请您尽快还款，谢谢。'
  },
  {
    speaker: '思彤',
    img: 'https://img.alicdn.com/tfs/TB1NW9ZDMDqK1RjSZSyXXaxEVXa-516-516.png',
    speakerId: 'sitong',
    speechType: '儿童音',
    scene: '童声场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '孩子还不知道忧愁，白白胖胖的很可爱。'
  },
  {
    speaker: '小北',
    img: 'https://img.alicdn.com/tfs/TB1NW9ZDMDqK1RjSZSyXXaxEVXa-516-516.png',
    speakerId: 'xiaobei',
    speechType: '萝莉女声',
    scene: '童声场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '这个家伙还是一如既往的蛮横不讲理。'
  },
  {
    speaker: '艾彤',
    img: 'https://img.alicdn.com/tfs/TB1NW9ZDMDqK1RjSZSyXXaxEVXa-516-516.png',
    speakerId: 'aitong',
    speechType: '儿童音',
    scene: '童声场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '春秋时，宋国有一位农夫，他正在田里工作的时候，突然看见一只兔子往大树的方向快跑。'
  },
  {
    speaker: '艾薇',
    img: 'https://img.alicdn.com/tfs/TB1NW9ZDMDqK1RjSZSyXXaxEVXa-516-516.png',
    speakerId: 'aiwei',
    speechType: '萝莉女声',
    scene: '童声场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '老虎你别急，听我说。我是上帝派来做百兽之王的！你要是吃了我，那就是违背了上帝的命令！'
  },
  {
    speaker: '艾宝',
    img: 'https://img.alicdn.com/tfs/TB1NW9ZDMDqK1RjSZSyXXaxEVXa-516-516.png',
    speakerId: 'aibao',
    speechType: '萝莉女声',
    scene: '童声场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '又见面啦，试试对我说“我要听小猪佩奇”。'
  },
  {
    speaker: 'Harry',
    img: 'https://img.alicdn.com/tfs/TB1Qa9ZDMDqK1RjSZSyXXaxEVXa-517-517.png',
    speakerId: 'harry',
    speechType: '英音男声',
    scene: '英文场景',
    language: '英文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'Some of the provisions for the protection of minors have been included in the common position but not enough of them.'
  },
  {
    speaker: 'Abby',
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    speakerId: 'abby',
    speechType: '美音女声',
    scene: '英文场景',
    language: '英文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'We need to bring in an expert to deal with this problem.'
  },
  {
    speaker: 'Andy',
    img: 'https://img.alicdn.com/tfs/TB1Qa9ZDMDqK1RjSZSyXXaxEVXa-517-517.png',
    speakerId: 'andy',
    speechType: '美音男声',
    scene: '英文场景',
    language: '英文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'View the latest news and breaking news today.'
  },
  {
    speaker: 'Eric',
    img: 'https://img.alicdn.com/tfs/TB1Qa9ZDMDqK1RjSZSyXXaxEVXa-517-517.png',
    speakerId: 'eric',
    speechType: '英音男声',
    scene: '英文场景',
    language: '英文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'Its case and internal components are made entirely from recycled, organic materials.'
  },
  {
    speaker: 'Emily',
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    speakerId: 'emily',
    speechType: '英音女声',
    scene: '英文场景',
    language: '英文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'Saturday is better for me because I am meeting my parents on Sunday.'
  },
  {
    speaker: 'Luna',
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    speakerId: 'luna',
    speechType: '英音女声',
    scene: '英文场景',
    language: '英文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'George is at the pet store, looking at what kind of pet he might want to get for his birthday.'
  },
  {
    speaker: 'Luca',
    img: 'https://img.alicdn.com/tfs/TB1Qa9ZDMDqK1RjSZSyXXaxEVXa-517-517.png',
    speakerId: 'luca',
    speechType: '英音男声',
    scene: '英文场景',
    language: '英文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'Many lessons are boring, and he is very tired after doing gym.'
  },
  {
    speaker: 'Wendy',
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    speakerId: 'wendy',
    speechType: '英音女声',
    scene: '英文场景',
    language: '英文场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'Great, I hope you enjoy your dinner.'
  },
  {
    speaker: 'William',
    img: 'https://img.alicdn.com/tfs/TB1Qa9ZDMDqK1RjSZSyXXaxEVXa-517-517.png',
    speakerId: 'william',
    speechType: '英音男声',
    scene: '英文场景',
    language: '英文场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'Plans are already under way to start work on the project.'
  },
  {
    speaker: 'Olivia',
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    speakerId: 'olivia',
    speechType: '英音女声',
    scene: '英文场景',
    language: '英文场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'MR Li, The amount of your current bill is 2050 yuan ,which needs to be paid before april twenty-one.'
  },
  {
    speaker: '姗姗',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'shanshan',
    speechType: '粤语女声',
    scene: '方言场景',
    language: '标准粤文（简体）及粤英文混合场景',
    sampleRate: [8000, 16000, 24000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '当前客服繁忙，为免耽误您的时间，您可以尝试通过支付宝HK APP里面【客户服务】查询您嘅问题。'
  },
  {
    speaker: '艾媛',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'aiyuan',
    speechType: '知心姐姐',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '新鲜的微风吹动我的衣袂，如同爱人的鼻息吹着我的手一样。'
  },
  {
    speaker: '艾颖',
    img: 'https://img.alicdn.com/tfs/TB1WCzHbjMZ7e4jSZFOXXX7epXa-238-238.png',
    speakerId: 'aiying',
    speechType: '软萌童声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '小蚂蚁扛着沉重的饭粒跑了半天，累得他浑身冒汗。'
  },
  {
    speaker: '艾祥',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'aixiang',
    speechType: '磁性男声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '他望着渐行渐远的马车叹了口气，一转身，便消失在云雾当中。'
  },
  {
    speaker: '艾墨',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'aimo',
    speechType: '情感男声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '爹爹放心，我和大哥平日无事，便会去照顾他的。'
  },
  {
    speaker: '艾晔',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'aiye',
    speechType: '青年男声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '山顶上站着一位青年，剑眉钩鼻，一袭白衣，腰间有一柄青石宝剑。'
  },
  {
    speaker: '艾婷',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'aiting',
    speechType: '电台女声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '请你来的时候，带一朵微启的玫瑰，我将久久的，久久的轻嗅，这人世间不变的香痕。'
  },
  {
    speaker: '艾凡',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'aifan',
    speechType: '情感女声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '黑匣子里薛定谔的猫要么是死要么是活，与你是否打开黑匣子无关。'
  },
  {
    speaker: 'Lydia',
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    speakerId: 'lydia',
    speechType: '英中双语女声',
    scene: '英文场景',
    language: '英文及英中文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '大家好，我是来自英国的Lydia，我的中文说得还不错吧？'
  },
  {
    speaker: '小玥',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'chuangirl',
    speechType: '四川话女声',
    scene: '方言场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '现在给你放起，《黑猫警长》第八集《谁是凶手》。'
  },
  {
    speaker: '艾硕',
    img: 'https://img.alicdn.com/tfs/TB1VmzHbjMZ7e4jSZFOXXX7epXa-238-238.png',
    speakerId: 'aishuo',
    speechType: '自然男声',
    scene: '客服场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '您好刘晓梅女士，请您在明天零点前，确保卡内金额至少为八百九十七元九毛钱。'
  },
  {
    speaker: '艾德',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'aide',
    speechType: '新闻男声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '民航局共执行国际包机178架次，运送抗疫物资1635吨'
  },
  {
    speaker: '青青',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'qingqing',
    speechType: '台湾话女声',
    scene: '方言场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '小主人，我是您的智能小助手，有问题请吩咐我吧！'
  },
  {
    speaker: '翠姐',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'cuijie',
    speechType: '东北话女声',
    scene: '方言场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '在俺们东北，有一种解决，叫“咋整”'
  },
  {
    speaker: '小泽',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'xiaoze',
    speechType: '湖南重口音男声',
    scene: '方言场景',
    language: '纯中文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '早上好，今天长沙多云转晴，10度到17度，空气质量良。'
  },
  {
    speaker: '艾楠',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'ainan',
    speechType: '广告男声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '图案采用条纹设计，简洁印花，更加可爱童趣。'
  },
  {
    speaker: '艾浩',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'aihao',
    speechType: '资讯男声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '一旦入驻，这一板块的价格势必迅速高涨。'
  },
  {
    speaker: '艾茗',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'aiming',
    speechType: '诙谐男声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '在二战期间，布劳格加入杜邦公司进行科研工作。'
  },
  {
    speaker: '艾笑',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'aixiao',
    speechType: '资讯女声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '很多超市，自制食品俨然已经成为主打产品。'
  },
  {
    speaker: '艾厨',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'aichu',
    speechType: '舌尖男声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '撇净筒内浮沫，再放入洗净的原料和干贝，静等一锅美味的羹汤慢慢熬制。'
  },
  {
    speaker: '艾倩',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'aiqian',
    speechType: '资讯女声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '在敬茶时除了论资排辈，按部就班之外，还得先敬客人来宾，然后再敬自家人。'
  },
  {
    speaker: '智香',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'tomoka',
    speechType: '日语女声',
    scene: '多语种场景',
    language: '纯日文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'ぐっすり眠った後は、ずっと気分がよい。'
  },
  {
    speaker: '智也',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'tomoya',
    speechType: '日语男声',
    scene: '多语种场景',
    language: '纯日文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'にやりと笑って、賛成の意思を示した。'
  },
  {
    speaker: 'Annie',
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    speakerId: 'annie',
    speechType: '美语女声',
    scene: '英文场景',
    language: '纯英文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'After my flight, we used to see quite often.'
  },
  {
    speaker: '艾树',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'aishu',
    speechType: '资讯男声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '我开始有很多感慨，但感慨终究也只是感慨。'
  },
  {
    speaker: '艾茹',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'airu',
    speechType: '新闻女声',
    scene: '文学场景',
    language: '中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '大家一致认为：他亲临湖南考察，发表重要讲话，充分体现了对湖南工作的高度重视'
  },
  {
    speaker: '佳佳',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'jiajia',
    speechType: '粤语女声',
    scene: '方言场景',
    language: '标准粤文（简体）及粤英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '超低折扣，限时购买，活动期间每个账号仅可购买一次，千祈唔好错过。'
  },
  {
    speaker: 'Indah',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'indah',
    speechType: '印尼语女声',
    scene: '多语种场景',
    language: '纯印尼语场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'Dia memulai perjalanan yang akan mengubah jalan hidupnya.'
  },
  {
    speaker: '桃子',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'taozi',
    speechType: '粤语女声',
    scene: '方言场景',
    language: '支持标准粤文（简体）及粤英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '我五点再联系你, 廿分钟之后再见'
  },
  {
    speaker: '柜姐',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'guijie',
    speechType: '亲切女声',
    scene: '通用场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '欢迎进来的宝宝，没关注主播的，去关注一下主播噢。'
  },
  {
    speaker: 'Stella',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'stella',
    speechType: '知性女声',
    scene: '通用场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '宝宝们，下面给大家推荐下，我们的这款电动牙刷。'
  },
  {
    speaker: 'Stanley',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'stanley',
    speechType: '沉稳男声',
    scene: '通用场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '冬季是最能演绎叠穿的季节，只要你够大胆，时髦的造型，随时都能拥有。'
  },
  {
    speaker: 'Kenny',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'kenny',
    speechType: '沉稳男声',
    scene: '通用场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '现在大家看到的这件宝贝，可以预约保温，迷你小巧，能够均匀加热，美观大气。'
  },
  {
    speaker: 'Rosa',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'rosa',
    speechType: '自然女声',
    scene: '通用场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '亲爱的宝宝们，大家好，给大家推荐一款迪士尼女童内衣套装'
  },
  {
    speaker: 'Farah',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'farah',
    speechType: '马来语女声',
    scene: '多语种场景',
    language: '仅支持纯马来语场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'Proses keadilan hendaklah berlaku terhadap semua pihak dan tidak seharusnya wujud pilih kasih.'
  },
  {
    speaker: '马树',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'mashu',
    speechType: '儿童剧男声',
    scene: '通用场景',
    language: '通用场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '有一天，小主人又送来食物，小兔子迫不及待地跑过去挑黄豆和玉米吃。'
  },
  {
    speaker: '知琪',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'zhiqi',
    speechType: '温柔女声',
    scene: '超高清场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000, 48000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '春日阳光普照大地，正是踏春好时节。'
  },
  {
    speaker: '知厨',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'zhichu',
    speechType: '舌尖男声',
    scene: '超高清场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000, 48000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '这是一年中最美味的团聚，也注定是一顿百感交集的晚餐。'
  },
  {
    speaker: '小仙',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'xiaoxian',
    speechType: '亲切女声',
    scene: '直播场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '放心吧，我们家羽绒服做的非常好，很保暖，主播这点还是很有自信的。37号链接，上链接了哈！'
  },
  {
    speaker: '悦儿',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'yuer',
    speechType: '儿童剧女声',
    scene: '通用场景',
    language: '仅支持纯中文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '小兔子照猴子医生的话去做了，果然牙齿不疼了，身体也壮实了。'
  },
  {
    speaker: '猫小美',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'maoxiaomei',
    speechType: '活力女声',
    scene: '直播场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '我们这款电饭煲可是非常畅销的宝贝，心动的宝宝们，赶紧下单呀。'
  },
  {
    speaker: '知祥',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'zhixiang',
    speechType: '磁性男声',
    scene: '超高清场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000, 48000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '不久，法医便发现，死者的脚部有红豆大小的疤痕。'
  },
  {
    speaker: '知佳',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'zhijia',
    speechType: '标准女声',
    scene: '超高清场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000, 48000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '市民在北京奥林匹克公园，乐享周末休闲时光。'
  },
  {
    speaker: '知楠',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'zhinan',
    speechType: '广告男声',
    scene: '超高清场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000, 48000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '修身的版型剪裁，线条顺滑流畅，给人愉悦的视觉感受。'
  },
  {
    speaker: '知倩',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'zhiqian',
    speechType: '资讯女声',
    scene: '超高清场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000, 48000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '抄袭的背后是两家屡次产品雷同，同质化严重。'
  },
  {
    speaker: '知茹',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'zhiru',
    speechType: '新闻女声',
    scene: '超高清场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000, 48000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '科技产品面对面系列活动启动，为创新企业，提供个性化服务。'
  },
  {
    speaker: '知德',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'zhide',
    speechType: '新闻男声',
    scene: '超高清场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000, 48000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '经历了职业生涯的这次季后赛，他也品尝到其中的苦涩和遗憾。'
  },
  {
    speaker: '知飞',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'zhifei',
    speechType: '激昂解说',
    scene: '超高清场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000, 48000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '易大有已经破釜沉舟了，时间又不允许再往后拖。'
  },
  {
    speaker: '艾飞',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'aifei',
    speechType: '激昂解说',
    scene: '直播场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '林浩明正指挥操盘手操纵股价，肖克找上门来了解案情'
  },
  {
    speaker: '亚群',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'yaqun',
    speechType: '卖场广播',
    scene: '直播场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '年中大促，优惠不封顶，价格降到底。'
  },
  {
    speaker: '巧薇',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'qiaowei',
    speechType: '卖场广播',
    scene: '直播场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '如您在本商场一次性购物满指定金额，即可享受免费送货服务。'
  },
  {
    speaker: '大虎',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'dahu',
    speechType: '东北话男声',
    scene: '方言场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '你瞅啥，有本事你再瞅一试试？'
  },
  {
    speaker: 'ava',
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    speakerId: 'ava',
    speechType: '美语女生',
    scene: '英文场景',
    language: '仅支持纯英文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: 'To improve our brand recognition, it is necessary for our company to tap the new market.'
  },
  {
    speaker: '知伦',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'zhilun',
    speechType: '悬疑解说',
    scene: '超高清场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000, 24000, 48000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '而此时，生死未卜的程晓冬终于渐渐苏醒'
  },
  {
    speaker: '艾伦',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'ailun',
    speechType: '悬疑解说',
    scene: '直播场景',
    language: '支持中文及中英文混合场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '警察和黑道都饶不了她，所以动了杀心。'
  },
  {
    speaker: '杰力豆',
    img: 'https://gw.alipayobjects.com/mdn/rms_21fdb3/afts/img/A*YE7vTILXC_MAAAAAAAAAAAAAARQnAQ',
    speakerId: 'jielidou',
    speechType: '治愈童声',
    scene: '童声场景',
    language: '仅支持纯中文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '千里马高昂着头望着远方，好像随时要奔跑的样子'
  },
  {
    speaker: '知薇',
    img: 'https://img.alicdn.com/tfs/TB1NW9ZDMDqK1RjSZSyXXaxEVXa-516-516.png',
    speakerId: 'zhiwei',
    speechType: '萝莉女声',
    scene: '超高清场景',
    language: '仅支持纯中文场景',
    sampleRate: [8000, 16000, 24000, 48000],
    timestamp: '是',
    quality: '精品版',
    speechFrom: '官方',
    text: '任何小动物，都可以坐到鸵鸟的背上顺路回家。'
  },
  {
    speaker: '老铁',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'laotie',
    speechType: '东北老铁',
    scene: '直播场景',
    language: '仅支持纯中文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '宝宝们，老铁这回真心推荐，错过再等一年。'
  },
  {
    speaker: '老妹',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'laomei',
    speechType: '吆喝女声',
    scene: '直播场景',
    language: '仅支持纯中文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '让我们先来试试这个腮红，天呐，真是绝绝子啊'
  },
  {
    speaker: '艾侃',
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    speakerId: 'aikan',
    speechType: '天津话男声',
    scene: '方言场景',
    language: '仅支持纯中文场景',
    sampleRate: [8000, 16000],
    timestamp: '是',
    quality: '标准版',
    speechFrom: '官方',
    text: '人家说起，甭管多大岁数的女的，上到80，下到18，统称姐姐'
  },
  {
    speaker: 'Tala',
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    speakerId: 'tala',
    speechType: '菲律宾语女声',
    scene: '多语种场景',
    language: '仅支持菲律宾语场景',
    sampleRate: [8000, 16000],
    timestamp: '否',
    quality: '标准版',
    speechFrom: '官方',
    text: 'Mag bake lang ng isang bunch ng cupcakes at dekurasyunan ito ayon sa gusto.'
  }
]
