export default [
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '印地语',
    style: '印地语女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_abha',
    function: 'vcn.x2_abha',
    name: '艾伯哈',
    translation: '您好，欢迎使用科大讯飞语音合成系统，我是发音人Abha',
    text: 'नमस्कार, iFLYTEK के उच्चारण जोड़ने का सिस्टम प्रयोग करने में आपका स्वागत, मैं स्पीकर अभा हूँ |',
    language_type: '1',
    isdram: 'false',
    recommended: '新'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '韩语',
    style: '韩语女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_miya',
    function: 'vcn.x2_miya',
    name: 'miya',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: '안녕하세요. 음성 합성 시스템 사용 을 환영 합 니 다.',
    language_type: '1',
    isdram: 'false',
    recommended: '新'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '俄语',
    style: '俄语女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_keshu',
    function: 'vcn.x2_keshu',
    name: 'keshu',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: 'Здравствуйте, добро пожаловать пользоваться синтезированной голосовой системой',
    language_type: '1',
    isdram: 'false',
    recommended: '新'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '意大利语',
    style: '意大利语女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_lrina',
    function: 'vcn.x2_lrina',
    name: 'lrina',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: 'Salve, benvenuto al sistema vocale sintetico iFLYTEK',
    language_type: '1',
    isdram: 'false',
    recommended: '新'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '西班牙语',
    style: '西班牙语女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_felisa',
    function: 'vcn.x2_felisa',
    name: 'felisa',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: 'Hola. Bienvenido al sistema de voz sintética.',
    language_type: '1',
    isdram: 'false',
    recommended: '新'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '波兰语',
    style: '波兰女声',
    info: '亲切自然、年轻朴实',
    code: 'natali',
    function: 'vcn.x2_natali',
    name: 'natali',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: 'Witam, witamy w systemie sztucznego głosu iFLYTEK',
    language_type: '1',
    isdram: 'false',
    recommended: '新'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '法语',
    style: '法语女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_mariane',
    function: 'vcn.x2_mariane',
    name: '玛丽安',
    translation: '您好，欢迎使用科大讯飞语音合成系统，我是发音人Mariane',
    text: 'Bonjour. Bienvenue sur le système de synthèse vocale iFLYTEK, je suis la locutrice: Mariane.། ',
    language_type: '1',
    isdram: 'false',
    recommended: '新'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '泰语',
    style: '泰语女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_suparut',
    function: 'vcn.x2_suparut',
    name: 'suparut',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: 'สวัสดีครับยินดีต้อนรับสู่การใช้ระบบสังเคราะห์เสียง',
    language_type: '1',
    isdram: 'false',
    recommended: '新'
  },
  {
    age: '成年女声',
    scene: '阅读场景',
    style: '温婉女声',
    info: '亲切自然、年轻朴实',
    code: 'xiaowan',
    function: 'vcn.x2_xiaowan',
    name: '小婉',
    text: '幸福原本很简单，拥有一份淡泊心志，观天空云卷云舒，品人生起起落落，在生命长河里活出自己的那份精彩，在喧嚣尘世里活出自己的一份坦然。',
    recommended: '新'
  },
  {
    age: '成年女声',
    scene: '阅读场景',
    style: '情感女声',
    info: '亲切自然、年轻朴实',
    code: 'qianxue2',
    function: 'vcn.x2_qianxue2',
    name: '千雪-情感',
    text: '山城妇科医院内，好友沈娇然的声音传来，打破了顾遇晚心中最后的一道防线。“一百万，能救你妈妈的性命，晚晚你还在犹豫什么！”孩子一出生就被安排好的人抱走，顾遇晚看着空空如也的病房，突然开始挣扎起来。',
    recommended: '新'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '日语',
    style: '日语女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_zhongcun',
    function: 'vcn.x2_zhongcun',
    name: 'zhongcun',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: 'すみません、科大訊飛合成音声システムをご利用ください。',
    language_type: '1',
    isdram: 'false',
    recommended: '新'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '马来语',
    style: '马来女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_malayrole',
    function: 'vcn.x2_malayrole',
    name: 'malayrole',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: 'Hello, selamat datang ke sistem suara sintetik iFLYTEK',
    language_type: '1',
    isdram: 'false',
    recommended: '新'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '德语',
    style: '德语女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_christiane',
    function: 'vcn.x2_christiane',
    name: 'christiane',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: 'Hallo, willkommen bei iFLYTEK Synthetic Voice System',
    language_type: '1',
    isdram: 'false',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '新闻',
    domain: '阅读场景',
    age: '成年女声',
    style: '清澈女声',
    info: '稳重磁性、大气成熟',
    code: 'x2_qianxue',
    function: 'vcn.x2_qianxue',
    name: '千雪',
    text: '五年后，顾遇晚穿着厚重的外套，穿梭在炎炎夏日中，她手上拿着一叠传单，人来人往的街道却没有人多看她一眼。就在顾遇晚摘掉头套的那一瞬间，耳边传来讥笑声。',
    recommended: '新',
    isdram: 'false'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '新闻',
    domain: '内蒙古方言、纪录片、阅读场景、阅读场景、课件文本',
    age: '成年男声',
    style: '内蒙古男声',
    info: '亲切自然、年轻朴实',
    code: 'x2_xiaobao',
    function: 'vcn.x2_xiaobao',
    name: '小包',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '新闻',
    domain: '合肥方言、纪录片、阅读场景、阅读场景、课件文本',
    age: '成年男声',
    style: '合肥男声',
    info: '亲切自然、年轻朴实',
    code: 'x2_xiaofei',
    function: 'vcn.x2_xiaofei',
    name: '小肥',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '新闻',
    domain: '阅读场景',
    age: '成年女声',
    style: '稳重女声',
    info: '稳重磁性、大气成熟',
    code: 'x2_xiaoguo',
    function: 'vcn.x2_xiaoguo',
    name: '小果',
    text: '白皮书说，党的十八大以来，中国的核安全事业进入安全高效发展的新时期。在核安全观引领下，中国逐步构建起法律规范、行政监管、行业自律、技术保障、人才支撑、文化引领、社会参与、国际合作等为主体的核安全治理体系，核安全防线更加牢固。',
    recommended: '新',
    isdram: 'false'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '新闻',
    domain: '河南方言、纪录片、阅读场景、阅读场景、课件文本',
    age: '成年男声',
    style: '河南男声',
    info: '亲切自然、年轻朴实',
    code: 'x2_xiaokun',
    function: 'vcn.x2_xiaokun',
    name: '小坤',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '新闻',
    domain: '山东方言、纪录片、阅读场景、阅读场景、课件文本',
    age: '成年女声',
    style: '山东女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_xiaodong',
    function: 'vcn.x2_xiaodong',
    name: '小东',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '新闻',
    domain: '东北方言、纪录片、阅读场景、阅读场景、课件文本',
    age: '成年女声',
    style: '东北女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_xiaoqian',
    function: 'vcn.x2_xiaoqian',
    name: '晓倩',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '新闻',
    domain: '四川方言、纪录片、阅读场景、阅读场景、课件文本',
    age: '成年女声',
    style: '四川女声',
    info: '亲切自然、年轻朴实',
    code: 'x_xiaorong',
    function: 'vcn.x2_xiaorong',
    name: '小蓉',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '新闻',
    domain: '湖北方言、纪录片、阅读场景、阅读场景、课件文本',
    age: '成年男声',
    style: '湖北男声',
    info: '亲切自然、年轻朴实',
    code: 'x2_xiaowang',
    function: 'vcn.x2_xiaowang',
    name: '小王',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '新闻',
    domain: '陕西方言、纪录片、阅读场景、阅读场景、课件文本',
    age: '成年女声',
    style: '陕西女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_xiaoying',
    function: 'vcn.x2_xiaoying',
    name: '小莹',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '新闻',
    domain: '湖南方言、纪录片、阅读场景、阅读场景、课件文本',
    age: '成年男声',
    style: '湖南男声',
    info: '亲切自然、年轻朴实',
    code: 'x2_xiaoqiang',
    function: 'vcn.x2_xiaoqiang',
    name: '小强',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景、阅读场景、中英混合',
    type: '新闻',
    domain: '通用场景、阅读场景、阅读场景、中英混合',
    age: '成年男声',
    style: '磁性男声',
    info: '稳重磁性、大气成熟',
    code: 'x_qige',
    function: 'vcn.x_qige',
    name: '七哥',
    text: '这本书的作者是来自于Harvard University的 Stephen curry，Stephen curry在他的书中提出了一种LSTM模型，这个LSTM模型很好的解释了wave-particle duality 现象。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景、交互场景',
    type: '小说',
    domain: '通用场景、交互场景',
    age: '成年女声',
    style: '亲切女声',
    info: '年轻时尚、亲切自然',
    code: 'x2_yezi',
    function: 'vcn.x2_yezi',
    name: '小露',
    text: '正在为您查询合肥的天气情况。今天是2020年2月24日，合肥市今天多云，最低温度9摄氏度，最高温度15摄氏度，微风。',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景、客服场景',
    type: '小说',
    domain: '通用场景、客服场景',
    age: '成年女声',
    style: '甜美女声',
    info: '年轻时尚、亲切自然',
    code: 'x2_yifei',
    function: 'vcn.x2_yifei',
    name: '一菲',
    text: '您好，我是客户回访专员，为了更好的爱护您的车辆，请您在一到两个月内或3000公里左右来店进行车辆首保。首保是免费的，我们的服务顾问和维修技师会为您的车做一次全面的检查。',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '小说',
    domain: '交互场景',
    age: '成年女声',
    style: '甜美女声',
    info: '年轻时尚、亲切自然',
    code: 'x_jiajia',
    function: 'vcn.x_jiajia',
    name: '嘉嘉',
    text: '正在为您查询合肥的天气情况。今天是2020年2月24日，合肥市今天多云，最低温度9摄氏度，最高温度15摄氏度，微风。',
    isdram: 'false',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景、阅读场景、中英混合',
    type: '新闻',
    domain: '通用场景、阅读场景、中英混合',
    age: '成年男声',
    style: '磁性男声',
    info: '稳重磁性、年轻时尚',
    code: 'x_chaoge',
    function: 'vcn.x_chaoge',
    name: '超哥',
    text: '这本书的作者是来自于Harvard University的 Stephen curry，Stephen curry在他的书中提出了一种LSTM模型，这个LSTM模型很好的解释了wave-particle duality 现象。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '新闻',
    domain: '儿童读物、有声文章',
    age: '男童声',
    style: '可爱男童',
    info: '可爱甜美、自然活泼',
    code: 'x_nannan',
    function: 'vcn.x_nannan',
    name: '楠楠',
    text: '布娃娃，别生气。布娃娃，你别生气，我来给你赔个礼。刚才不该发脾气，使劲把你扔在地。弄脏了你的新花衣，摔得你脸上都是泥。一定还很疼吧?真是对不起！衣服脏了我给你拍，脸儿脏了我给你洗，从今以后，我要爱护你。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '新闻',
    domain: '阅读场景、阅读场景、课件文本',
    age: '成年男声',
    style: '成熟男声',
    info: '稳重磁性、大气成熟',
    code: 'x_wanshu',
    function: 'vcn.x_wanshu',
    name: '万叔',
    text: '白皮书说，党的十八大以来，中国的核安全事业进入安全高效发展的新时期。在核安全观引领下，中国逐步构建起法律规范、行政监管、行业自律、技术保障、人才支撑、文化引领、社会参与、国际合作等为主体的核安全治理体系，核安全防线更加牢固。',
    isdram: 'false',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '客服场景',
    type: '客服',
    domain: '客服场景',
    age: '成年女声',
    style: '亲切女声',
    info: '亲切自然、时尚甜美',
    code: 'x2_xiaomo',
    function: 'vcn.x2_xiaomo',
    name: '小莫',
    text: '您好，我是客户回访专员，为了更好的爱护您的车辆，请您在一到两个月内或3000公里左右来店进行车辆首保。首保是免费的，我们的服务顾问和维修技师会为您的车做一次全面的检查。',
    isdram: 'false',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '小说',
    domain: '有声文章、阅读场景、专题宣传',
    age: '成年男声',
    style: '磁性男声',
    info: '稳重磁性、自然亲切',
    code: 'x_xiaoxi',
    function: 'vcn.x_xiaoxi',
    name: '水哥',
    text: '长城是古代中国在不同时期，为抵御塞北游牧部落侵袭而修筑的规模浩大的军事工程。长城绵延上万华里，因此又称作万里长城。现存的长城遗迹，西起嘉峪关，东至辽东虎山，全长8851.8公里，平均高6至7米、宽4至5米。长城是我国古代劳动人民创造的伟大的奇迹，是中国古代人民智慧的结晶，是中国悠久历史的见证。它与天安门，兵马俑一起被世人视为中国的象征。长城欢迎您！',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '客服场景',
    type: '客服',
    domain: '客服场景',
    age: '成年女声',
    style: '亲切女声',
    info: '亲切自然、时尚甜美',
    code: 'x2_xiaoya',
    function: 'vcn.x2_xiaoya',
    name: '小雅',
    text: '您好，我是客户回访专员，为了更好的爱护您的车辆，请您在一到两个月内或3000公里左右来店进行车辆首保。首保是免费的，我们的服务顾问和维修技师会为您的车做一次全面的检查。',
    isdram: 'false',
    recommended: '新'
  },
  {
    speaker: '精品发音人',
    scene: '阅读场景',
    type: '/',
    domain: '阅读场景',
    age: '成年男声',
    style: '磁性男声',
    info: '稳重磁性、亲切自然',
    code: 'x2_yifeng',
    function: 'vcn.x2_yifeng',
    name: '一峰',
    text: '白皮书说，党的十八大以来，中国的核安全事业进入安全高效发展的新时期。在核安全观引领下，中国逐步构建起法律规范、行政监管、行业自律、技术保障、人才支撑、文化引领、社会参与、国际合作等为主体的核安全治理体系，核安全防线更加牢固。',
    isdram: 'false',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '小说',
    domain: '有声文章、专题宣传、纪录片',
    age: '成年男声',
    style: '磁性男声',
    info: '稳重磁性、亲切自然',
    code: 'x_yuanye',
    function: 'vcn.x_yuanye',
    name: '易阳泽',
    text: '在中国大陆和宝岛台湾之间，一片浩浩淼淼的水域，如繁星般洒落着千礁百岛，海阔潮涌，天风吹梦。这就是福建平潭。平潭岛上的人们生来与海为伴，世代搏击于风口浪尖。一方水土养一方人，特殊的环境，孕育了岛民刚毅、豪迈、执着、拼搏的海洋文化精神。正是凭借着这种敢于担当、不避艰险、勇于开拓的冲劲和豪情，这里的人们创造了许许多多商业奇迹，宏扬了海纳百川、四海为家、敢拼会赢的“闽商”特质。',
    isdram: 'false',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景',
    type: '小说',
    domain: '通用场景',
    age: '成年男声',
    style: '成熟男声',
    info: '年轻时尚、亲切自然',
    code: 'x2_pengfei',
    function: 'vcn.x2_pengfei',
    name: '小鹏',
    text: '在已经过去的2001年，人类已经在太空中建立起壮丽的城市，在月球上建立起永久性的殖民地，巨大的核动力飞船已经航行到土星。而在现实中的2018年，再也没有人登上月球，人类的太空中航行的最远的距离，也就是途经我所在的城市的高速列车两个小时的里程。',
    isdram: 'false',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '小说',
    domain: '阅读场景、阅读场景、专题宣传',
    age: '成年男声',
    style: '时尚男声',
    info: '年轻时尚、亲切自然',
    code: 'x_xiaohou',
    function: 'vcn.x_xiaohou',
    name: '逍遥子',
    text: '长城是古代中国在不同时期，为抵御塞北游牧部落侵袭而修筑的规模浩大的军事工程。长城绵延上万华里，因此又称作万里长城。现存的长城遗迹，西起嘉峪关，东至辽东虎山，全长8851.8公里，平均高6至7米、宽4至5米。长城是我国古代劳动人民创造的伟大的奇迹，是中国古代人民智慧的结晶，是中国悠久历史的见证。它与天安门，兵马俑一起被世人视为中国的象征。长城欢迎您！',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '客服场景',
    type: '客服',
    domain: '客服场景',
    age: '成年女声',
    style: '亲切女声',
    info: '亲切自然、时尚甜美',
    code: 'x2_xiaolan',
    function: 'vcn.x2_xiaolan',
    name: '小兰',
    text: '您好，我是客户回访专员，为了更好的爱护您的车辆，请您在一到两个月内或3000公里左右来店进行车辆首保。首保是免费的，我们的服务顾问和维修技师会为您的车做一次全面的检查。',
    isdram: 'false',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景、交互场景',
    type: '娱乐',
    domain: '声似明星、儿童读物、有声文章',
    age: '男童声',
    style: '可爱男童',
    info: '可爱呆萌',
    code: 'x_xiaoxin',
    function: 'vcn.x_xiaoxin',
    name: '萌小新',
    text: '布娃娃，别生气。布娃娃，你别生气，我来给你赔个礼。刚才不该发脾气，使劲把你扔在地。弄脏了你的新花衣，摔得你脸上都是泥。一定还很疼吧?真是对不起！衣服脏了我给你拍，脸儿脏了我给你洗，从今以后，我要爱护你。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景、客服场景、中英混合',
    type: '交互',
    domain: '阅读场景、客服场景、交互场景、有声文章',
    age: '成年女声',
    style: '知性女声',
    info: '成熟知性、干净利落、自然饱满',
    code: 'x_xiaoxue',
    function: 'vcn.x_xiaoxue',
    name: '小雪',
    text: '这本书的作者是来自于Harvard University的 Stephen curry，Stephen curry在他的书中提出了一种LSTM模型，这个LSTM模型很好的解释了wave-particle duality 现象。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '交互',
    domain: '儿童读物、有声文章',
    age: '男童声',
    style: '可爱男童',
    info: '可爱甜美、亲切自然',
    code: 'x_ningning',
    function: 'vcn.x_ningning',
    name: '宁宁',
    text: '美丽的小白兔穿着漂亮的花裙子，哼着歌，蹦蹦跳跳地上了桥，它要到对面去采蘑菇。就在这时候，它看见对面的山羊伯伯也准备要过桥。小桥很窄，只能一个人过桥。小白兔看见了，停下脚步，大声说：“山羊伯伯您先过桥吧！”说完，它就从桥上退了下来。山羊伯伯过了桥，摸着小白兔的头夸奖道：“你真乖！”',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '客服场景',
    type: '交互',
    domain: '客服场景、交互场景、阅读场景',
    age: '成年女声',
    style: '亲切女声',
    info: '亲切自然、成熟稳重',
    code: 'x_xiaoding',
    function: 'vcn.x_xiaoding',
    name: '小丁',
    text: '您好，欢迎来到科大讯飞。您好，请问有什么可以帮您？正在为您查询，请稍等。感谢您的来电，祝您生活愉快。',
    recommended: '新升级'
  },
  {
    speaker: '精品发音人',
    scene: '交互场景',
    type: '小说',
    domain: '交互场景',
    age: '女童声',
    style: '可爱女童',
    info: '可爱甜美、自然活泼',
    code: 'x_xiaofang',
    function: 'vcn.x_xiaofang',
    name: '芳芳',
    text: '布娃娃，别生气。布娃娃，你别生气，我来给你赔个礼。刚才不该发脾气，使劲把你扔在地。弄脏了你的新花衣，摔得你脸上都是泥。一定还很疼吧?真是对不起！衣服脏了我给你拍，脸儿脏了我给你洗，从今以后，我要爱护你。',
    recommended: '新升级'
  },
  {
    speaker: '精品发音人',
    scene: '阅读场景',
    type: '/',
    domain: '阅读场景',
    age: '成年男声',
    style: '磁性男声',
    info: '稳重磁性、亲切自然',
    code: 'x2_xiaofeng',
    function: 'vcn.x2_xiaofeng',
    name: '晓峰',
    text: '白皮书说，党的十八大以来，中国的核安全事业进入安全高效发展的新时期。在核安全观引领下，中国逐步构建起法律规范、行政监管、行业自律、技术保障、人才支撑、文化引领、社会参与、国际合作等为主体的核安全治理体系，核安全防线更加牢固。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '客服场景',
    type: '客服',
    domain: '客服场景',
    age: '成年女声',
    style: '亲切女声',
    info: '亲切自然、时尚甜美',
    code: 'x2_xiaojuan',
    function: 'vcn.x2_xiaojuan',
    name: '小娟',
    text: '您好，我是客户回访专员，为了更好的爱护您的车辆，请您在一到两个月内或3000公里左右来店进行车辆首保。首保是免费的，我们的服务顾问和维修技师会为您的车做一次全面的检查。',
    isdram: 'false',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '小说',
    domain: '交互场景',
    age: '成年女声',
    style: '甜美女声',
    info: '年轻时尚、亲切自然',
    code: 'x2_xiaoxuan',
    function: 'vcn.x2_xiaoxuan',
    name: '晓璇',
    text: '正在为您查询合肥的天气情况。今天是2020年2月24日，合肥市今天多云，最低温度9摄氏度，最高温度15摄氏度，微风。',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景、中英混合',
    type: '新闻',
    domain: '课件文本、阅读场景、阅读场景',
    age: '成年女声',
    style: '时尚女声',
    info: '年轻时尚、亲切自然',
    code: 'x_xiaoyuan',
    function: 'vcn.x_xiaoyuan',
    name: '小媛',
    text: '这本书的作者是来自于Harvard University的 Stephen curry，Stephen curry在他的书中提出了一种LSTM模型，这个LSTM模型很好的解释了wave-particle duality 现象。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '多语种场景',
    type: '新闻',
    domain: '课件文本、阅读场景、阅读场景',
    age: '成年女声',
    style: '英文女声',
    info: '成熟知性、亲切自然',
    code: 'x_catherine',
    function: 'vcn.x_catherine',
    name: '凯瑟琳',
    text: "My father, brother and I visited West Point to see a football game between Army and Boston College. Taking a stroll before kickoff, we met many cadets in neatly pressed uniforms. Several visting fans asked the recruits if they would pose for photographs, 'to show our son what to expect if he should attend West Point.'One middle-aged couple approached a very attractive female cadet and asked her to pose for a picture. They explained, 'We want to show our son what he missed by not coming to West Point.' ",
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '小说',
    domain: '有声文章、专题宣传、纪录片',
    age: '成年男声',
    style: '磁性男声',
    info: '稳重磁性、自然亲切',
    code: 'x_dahuilang',
    function: 'vcn.x_dahuilang',
    name: '康铭',
    text: '在中国大陆和宝岛台湾之间，一片浩浩淼淼的水域，如繁星般洒落着千礁百岛，海阔潮涌，天风吹梦。这就是福建平潭。平潭岛上的人们生来与海为伴，世代搏击于风口浪尖。一方水土养一方人，特殊的环境，孕育了岛民刚毅、豪迈、执着、拼搏的海洋文化精神。正是凭借着这种敢于担当、不避艰险、勇于开拓的冲劲和豪情，这里的人们创造了许许多多商业奇迹，宏扬了海纳百川、四海为家、敢拼会赢的“闽商”特质。',
    isdram: 'false',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '交互',
    domain: '儿童读物、有声文章',
    age: '女童声',
    style: '可爱女童',
    info: '可爱甜美、亲切自然',
    code: 'x2_xiaowanzi',
    function: 'vcn.x2_xiaowanzi',
    name: '小桃丸',
    text: '美丽的小白兔穿着漂亮的花裙子，哼着歌，蹦蹦跳跳地上了桥，它要到对面去采蘑菇。就在这时候，它看见对面的山羊伯伯也准备要过桥。小桥很窄，只能一个人过桥。小白兔看见了，停下脚步，大声说：“山羊伯伯您先过桥吧！”说完，它就从桥上退了下来。山羊伯伯过了桥，摸着小白兔的头夸奖道：“你真乖！”',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '交互',
    domain: '客服场景、交互场景、阅读场景',
    age: '成年男声',
    style: '浑厚男声',
    info: '亲切自然、磁性浑厚',
    code: 'x_xiaozhang',
    function: 'vcn.x_xiaozhang',
    name: '刚哥',
    text: '当时，我每天白天要采访读者，并对采访结果进行统计和总结；晚上，公司会聘请大学老师为我们讲授统计学和心理学的课程。',
    isdram: 'false',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '客服场景',
    type: '交互',
    domain: '客服场景、交互场景、阅读场景',
    age: '成年女声',
    style: '温柔女声',
    info: '温柔甜美、亲切自然',
    code: 'x_chongchong',
    function: 'vcn.x_chongchong',
    name: '虫虫',
    text: '您好，欢迎来到科大讯飞。您好，请问有什么可以帮您？正在为您查询，请稍等。感谢您的来电，祝您生活愉快。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '新闻',
    domain: '阅读场景、有声文章、纪录片、幽默段子',
    age: '成年男声',
    style: '和蔼男声',
    info: '稳重和蔼、自然亲切',
    code: 'x_laoma',
    function: 'vcn.x_laoma',
    name: '马叔',
    text: '长城是古代中国在不同时期，为抵御塞北游牧部落侵袭而修筑的规模浩大的军事工程。长城绵延上万华里，因此又称作万里长城。现存的长城遗迹，西起嘉峪关，东至辽东虎山，全长8851.8公里，平均高6至7米、宽4至5米。长城是我国古代劳动人民创造的伟大的奇迹，是中国古代人民智慧的结晶，是中国悠久历史的见证。它与天安门，兵马俑一起被世人视为中国的象征。长城欢迎您！'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '新闻',
    domain: '阅读场景、阅读场景',
    age: '成年女声',
    style: '知性女声',
    info: '温柔知性、亲切自然',
    code: 'x_jinger',
    function: 'vcn.x_jinger',
    name: '晓婧',
    text: '白皮书说，党的十八大以来，中国的核安全事业进入安全高效发展的新时期。在核安全观引领下，中国逐步构建起法律规范、行政监管、行业自律、技术保障、人才支撑、文化引领、社会参与、国际合作等为主体的核安全治理体系，核安全防线更加牢固。'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '小说',
    domain: '有声文章、纪录片、专题宣传',
    age: '成年女声',
    style: '亲切女声',
    info: '亲切自然、温柔知性',
    code: 'x2_yiping',
    function: 'vcn.x2_yiping',
    name: '一萍',
    text: '在中国大陆和宝岛台湾之间，一片浩浩淼淼的水域，如繁星般洒落着千礁百岛，海阔潮涌，天风吹梦。这就是福建平潭。平潭岛上的人们生来与海为伴，世代搏击于风口浪尖。一方水土养一方人，特殊的环境，孕育了岛民刚毅、豪迈、执着、拼搏的海洋文化精神。正是凭借着这种敢于担当、不避艰险、勇于开拓的冲劲和豪情，这里的人们创造了许许多多商业奇迹，宏扬了海纳百川、四海为家、敢拼会赢的“闽商”特质。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '小说',
    domain: '纪录片、专题宣传、有声文章',
    age: '成年男声',
    style: '磁性男声',
    info: '稳重磁性、成熟亲切',
    code: 'x_xiaowei',
    function: 'vcn.x_xiaowei',
    name: '小魏',
    text: '在中国大陆和宝岛台湾之间，一片浩浩淼淼的水域，如繁星般洒落着千礁百岛，海阔潮涌，天风吹梦。这就是福建平潭。平潭岛上的人们生来与海为伴，世代搏击于风口浪尖。一方水土养一方人，特殊的环境，孕育了岛民刚毅、豪迈、执着、拼搏的海洋文化精神。正是凭借着这种敢于担当、不避艰险、勇于开拓的冲劲和豪情，这里的人们创造了许许多多商业奇迹，宏扬了海纳百川、四海为家、敢拼会赢的“闽商”特质。'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景',
    type: '新闻',
    domain: '声似明星、客服场景、交互场景、有声文章',
    age: '成年女声',
    style: '温柔女声',
    info: '温柔甜美、年轻时尚、亲切自然',
    code: 'x_xiaoling',
    function: 'vcn.x_xiaoling',
    name: '玲姐姐',
    text: '您好，欢迎来到科大讯飞。您好，请问有什么可以帮您？正在为您查询，请稍等。感谢您的来电，祝您生活愉快。',
    isdram: 'false'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景',
    type: '新闻',
    domain: '声似明星、客服场景、交互场景、有声文章',
    age: '成年男声',
    style: '亲切男声',
    info: '饱满活泼、亲切自然',
    code: 'x_xiaosong',
    function: 'vcn.x_xiaosong',
    name: '宋宝宝',
    text: '您好，欢迎来到科大讯飞。您好，请问有什么可以帮您？正在为您查询，请稍等。感谢您的来电，祝您生活愉快。',
    isdram: 'false'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '客服',
    domain: '客服场景、交互场景',
    age: '成年女声',
    style: '甜美女声',
    info: '亲切甜美、年轻时尚',
    code: 'x2_xiaoshi_cts',
    function: 'vcn.x2_xiaoshi_cts',
    name: '小师',
    text: '您好，欢迎来到科大讯飞。您好，请问有什么可以帮您？正在为您查询，请稍等。感谢您的来电，祝您生活愉快。',
    recommended: '新升级'
  },
  {
    age: '成年女声',
    scene: '民族语言场景',
    languages: '维吾尔语',
    style: '维吾尔语女声',
    info: '亲切自然、年轻朴实',
    code: 'guli',
    function: 'vcn.guli',
    name: '古丽',
    translation:
      '您好，欢迎使用新疆大学讯飞维吾尔语语音合成系统，我是发音人古丽娜尔',
    text: 'ياخشىمۇسىز، شىنجاڭ ئۇنىۋېرسىتېتى شۈنفېي ئاۋاز كىرىشتۈرۈش سېستىمىسىنى ئىشلىتىشىڭىزنى قىزغىن قارشى ئالىمىز،  مەن گۈلنۇر بولىمەن.',
    language_type: '1'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '乌尔都语',
    style: '乌尔都语女声',
    info: '亲切自然、年轻朴实',
    code: 'baili',
    function: 'vcn.baili',
    name: '百利',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: 'ہیلو ، یونیورسٹی آف سائنس اینڈ ٹکنالوجی فلائٹ اسپیچ ترکیب نظام کو استعمال کرنے میں خوش آمدید',
    language_type: '1'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '意大利语',
    style: '意大利语女声',
    info: '亲切自然、年轻朴实',
    code: 'barbm',
    function: 'vcn.barbm',
    name: '巴尔姆',
    translation: '您好，欢迎使用科大讯飞语音合成系统，我是发音人Alessia',
    text: 'Buongiorno, grazie per usare il sistema sintesi vocale di iFLYTEK, sono Alessia',
    language_type: '1'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '葡萄牙语',
    style: '葡萄牙语女声',
    info: '亲切自然、年轻朴实',
    code: 'maria',
    function: 'vcn.maria',
    name: '玛利亚',
    translation: '您好，欢迎使用科大讯飞语音合成系统，我是发音人Sonia',
    text: 'Olá, bem-vindo a utilizar o Sistema de Fonética Sintética de iFLYTEK, sou Sonia.',
    language_type: '1'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '巴西葡萄牙语',
    style: '巴西葡萄牙语女声',
    info: '亲切自然、年轻朴实',
    code: 'sonia',
    function: 'vcn.sonia',
    name: '索尼亚',
    translation: '您好，欢迎使用科大讯飞语音合成系统，我是发音人Sonia',
    text: 'Olá, bem-vindo a utilizar o Sistema de Fonética Sintética de iFLYTEK, sou Sonia.',
    language_type: '1'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '德语',
    style: '德语女声',
    info: '亲切自然、年轻朴实',
    code: 'leonie',
    function: 'vcn.leonie',
    name: '莱昂尼',
    translation: '您好，欢迎使用科大讯飞语音合成系统，我是发音人Anna',
    text: 'Guten Tag, ich begrüße Sie ganz herzlich zu unserem Sprachsynthesesystem von iFlytek. Ich bin die Sprecherin Anna.',
    language_type: '1'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '故事',
    domain: '儿童读物、有声文章',
    age: '女童声',
    style: '可爱女童',
    info: '可爱呆萌、甜美亲切',
    code: 'x_lele',
    function: 'vcn.x_lele',
    name: '乐乐',
    text: '布娃娃，别生气。布娃娃，你别生气，我来给你赔个礼。刚才不该发脾气，使劲把你扔在地。弄脏了你的新花衣，摔得你脸上都是泥。一定还很疼吧?真是对不起！衣服脏了我给你拍，脸儿脏了我给你洗，从今以后，我要爱护你。'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '新闻',
    domain: '台湾普通话、纪录片、阅读场景、阅读场景、课件文本',
    age: '成年女声',
    style: '台湾女声',
    info: '亲切自然、时尚甜美',
    code: 'x_yuer',
    function: 'vcn.x_yuer',
    name: '玉儿',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '韩语',
    style: '韩语女声',
    info: '亲切自然、年轻朴实',
    code: 'zhimin',
    function: 'vcn.zhimin',
    name: '智敏',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: '안녕하세요. 과학 기술 비행 음성 합성 시스템 대학을 이용해 주셔서 감사합니다',
    language_type: '1'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '日语',
    style: '日语女声',
    info: '亲切自然、年轻朴实',
    code: 'qianhui',
    function: 'vcn.qianhui',
    name: '千惠',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: 'こんにちは、科学技術大学のフライト音声合成システムの使用を歓迎します',
    language_type: '1'
  },
  {
    speaker: '特色发音人',
    scene: '多语种场景',
    type: '新闻',
    domain: '课件文本、阅读场景、阅读场景',
    age: '成年男声',
    style: '英文男声',
    info: '大气浑厚、稳重磁性、自然亲切',
    code: 'x2_john',
    function: 'vcn.x2_John',
    name: 'John',
    text: 'My father, brother and I visited West Point to see a football game between Army and Boston College. Taking a stroll before kickoff, we met many cadets in neatly pressed uniforms. Several visting fans asked the recruits if they would pose for photographs, to show our son what to expect if he should attend West Point.One middle-aged couple approached a very attractive female cadet and asked her to pose for a picture. They explained, We want to show our son what he missed by not coming to West Point.',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '多语种场景',
    type: '对话',
    domain: '课件文本、阅读场景、阅读场景、有声文章、专题宣传',
    age: '成年男声',
    style: '英文男声',
    info: '大气浑厚、稳重磁性、自然亲切',
    code: 'x_steve',
    function: 'vcn.x_Steve',
    name: 'Steve',
    text: "My father, brother and I visited West Point to see a football game between Army and Boston College. Taking a stroll before kickoff, we met many cadets in neatly pressed uniforms. Several visting fans asked the recruits if they would pose for photographs, 'o show our son what to expect if he should attend West Point.'One middle-aged couple approached a very attractive female cadet and asked her to pose for a picture. They explained, 'We want to show our son what he missed by not coming to West Point.' "
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '故事',
    domain: '儿童读物、有声文章',
    age: '女童声',
    style: '可爱女童',
    info: '可爱甜美、活泼自然',
    code: 'x_yuxin',
    function: 'vcn.x_yuxin',
    name: '馨馨',
    text: '布娃娃，别生气。布娃娃，你别生气，我来给你赔个礼。刚才不该发脾气，使劲把你扔在地。弄脏了你的新花衣，摔得你脸上都是泥。一定还很疼吧?真是对不起！衣服脏了我给你拍，脸儿脏了我给你洗，从今以后，我要爱护你。'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '越南语',
    style: '越南语女声',
    info: '亲切自然、年轻朴实',
    code: 'xiaoyun',
    function: 'vcn.xiaoyun',
    name: '小芸',
    translation: '您好，欢迎使用科大讯飞语音合成系统，我是发音人小云',
    text: 'Xin chào, rất hân hạnh mời bạn sử dụng hệ thống chuyển văn bản thành giọng nói của iFlyTek, tôi là phát thanh viên Tiểu Vân',
    language_type: '1'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '俄语',
    style: '俄语女声',
    info: '亲切自然、年轻朴实',
    code: 'allabent',
    function: 'vcn.allabent',
    name: '阿拉本特',
    translation: '您好，欢迎使用科大讯飞语音合成系统，我是发音人玛丽安',
    text: 'Здравствуйте! Добро пожаловать в синтетическую фонетическую систему ЗАО iFLYTEK. Я выступающий: Марианна',
    language_type: '1'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '西班牙语',
    style: '西班牙语女声',
    info: '亲切自然、年轻朴实',
    code: 'gabriela',
    function: 'vcn.gabriela',
    name: '加芙列得',
    translation: '您好，欢迎使用科大讯飞语音合成系统，我是发音人玛丽娅',
    text: 'Hola. Bienvenido a usar el sistema de síntesis vocal iFLYTEK. Soy la locutora: María.',
    language_type: '1'
  },
  {
    age: '成年女声',
    scene: '民族语言场景',
    languages: '维吾尔语',
    style: '维吾尔语女声',
    info: '亲切自然、年轻朴实',
    code: 'patiguli',
    function: 'vcn.patiguli',
    name: '帕蒂古里',
    translation:
      '您好，欢迎使用新疆大学讯飞维吾尔语语音合成系统，我是发音人古丽娜尔',
    text: 'ياخشىمۇسىز، شىنجاڭ ئۇنىۋېرسىتېتى شۈنفېي ئاۋاز كىرىشتۈرۈش سېستىمىسىنى ئىشلىتىشىڭىزنى قىزغىن قارشى ئالىمىز،  مەن گۈلنۇر بولىمەن.',
    language_type: '1'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '新闻',
    domain: '阅读场景、阅读场景',
    age: '成年女声',
    style: '知性女声',
    info: '稳重知性、亲切自然',
    code: 'x_xiaoru',
    function: 'vcn.x_xiaoru',
    name: '小茹',
    text: '白皮书说，党的十八大以来，中国的核安全事业进入安全高效发展的新时期。在核安全观引领下，中国逐步构建起法律规范、行政监管、行业自律、技术保障、人才支撑、文化引领、社会参与、国际合作等为主体的核安全治理体系，核安全防线更加牢固。'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景、阅读场景',
    type: '广告',
    domain: '广告促销、专题宣传、阅读场景',
    age: '成年女声',
    style: '甜美女声',
    info: '青春甜美、年轻时尚、自然亲切',
    code: 'x_yaoyao',
    function: 'vcn.x_yaoyao',
    name: '瑶瑶',
    text: '完美的港式奶茶，茶要够浓，奶也要够浓，入口幼滑如丝，不会一饮而泻，而是延绵细蜜，有奶油的口感。奶茶的厚度主要由淡奶及茶汤的浓淡决定，淡奶所含的奶脂一定要够浓，奶茶才能挂杯奶茶。而挂杯只算合格了一半，奶味绝对不能掩盖茶味，而且入口不能涩，才算一杯完美的挂杯港式奶茶。',
    isdram: 'false'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '哈萨克(西里尔)',
    style: '哈萨克(西里尔)女',
    info: '亲切自然、年轻朴实',
    code: 'x2_annakz',
    function: 'vcn.x2_annakz',
    name: 'annakz',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: 'Сәлем, iFLYTEK синтетикалық дыбыс жүйесіне қош келдіңіз',
    language_type: '1',
    isdram: 'false'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '小说',
    domain: '阅读场景',
    age: '成年男声',
    style: '磁性男声',
    info: '',
    code: 'x2_guange',
    function: 'vcn.x2_guange',
    name: '管哥',
    text: '白皮书说，党的十八大以来，中国的核安全事业进入安全高效发展的新时期。在核安全观引领下，中国逐步构建起法律规范、行政监管、行业自律、技术保障、人才支撑、文化引领、社会参与、国际合作等为主体的核安全治理体系，核安全防线更加牢固。',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '小说',
    domain: '阅读场景',
    age: '成年男声',
    style: '小说男声',
    info: '',
    code: 'x2_mingge',
    function: 'vcn.x2_mingge',
    name: '明哥',
    text: '在中国大陆和宝岛台湾之间，一片浩浩淼淼的水域，如繁星般洒落着千礁百岛，海阔潮涌，天风吹梦。这就是福建平潭。平潭岛上的人们生来与海为伴，世代搏击于风口浪尖。一方水土养一方人，特殊的环境，孕育了岛民刚毅、豪迈、执着、拼搏的海洋文化精神。正是凭借着这种敢于担当、不避艰险、勇于开拓的冲劲和豪情，这里的人们创造了许许多多商业奇迹，宏扬了海纳百川、四海为家、敢拼会赢的“闽商”特质。',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '小说',
    domain: '阅读场景',
    age: '成年男声',
    style: '小说男声',
    info: '',
    code: 'x2_tiange',
    function: 'vcn.x2_tiange',
    name: '天哥',
    text: '在中国大陆和宝岛台湾之间，一片浩浩淼淼的水域，如繁星般洒落着千礁百岛，海阔潮涌，天风吹梦。这就是福建平潭。平潭岛上的人们生来与海为伴，世代搏击于风口浪尖。一方水土养一方人，特殊的环境，孕育了岛民刚毅、豪迈、执着、拼搏的海洋文化精神。正是凭借着这种敢于担当、不避艰险、勇于开拓的冲劲和豪情，这里的人们创造了许许多多商业奇迹，宏扬了海纳百川、四海为家、敢拼会赢的“闽商”特质。',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景',
    type: '广告',
    domain: '广告促销',
    age: '成年男声',
    style: '热情男声',
    info: '热情洋溢、激情四射、年轻时尚',
    code: 'x_xiaojun',
    function: 'vcn.x_xiaojun',
    name: '小俊',
    text: '双十二来袭，狂欢继续，宇周商场感恩回馈，会员尊享折后立减，全场折后满221元立减12元， 买的多减的多，以此类推！童装精选超值特价三十九块九，女装精选特价59元起，男装部分低至99元，女鞋精选部分一件8折，两件7折，捷狮男鞋系列7折钜惠，一起去宇周买买买吧！',
    isdram: 'false'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '新闻',
    domain: '台湾普通话、纪录片、阅读场景、阅读场景、课件文本',
    age: '成年女声',
    style: '台湾女声',
    info: '亲切自然、时尚甜美',
    code: 'x_xiaolin',
    function: 'vcn.x_xiaolin',
    name: '晓琳',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '新闻',
    domain: '粤语文本、纪录片、阅读场景、阅读场景、课件文本',
    age: '成年女声',
    style: '广东女声',
    info: '亲切自然、年轻时尚',
    code: 'x_xiaomei',
    function: 'vcn.x_xiaomei',
    name: '小梅',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景',
    type: '广告',
    domain: '有声文章、纪录片、专题宣传、阅读场景',
    age: '成年女声',
    style: '知性女声',
    info: '温柔知性、自然亲切、年轻甜美',
    code: 'x_xiaonan',
    function: 'vcn.x_xiaonan',
    name: '小南',
    text: '长城是古代中国在不同时期，为抵御塞北游牧部落侵袭而修筑的规模浩大的军事工程。长城绵延上万华里，因此又称作万里长城。现存的长城遗迹，西起嘉峪关，东至辽东虎山，全长8851.8公里，平均高6至7米、宽4至5米。长城是我国古代劳动人民创造的伟大的奇迹，是中国古代人民智慧的结晶，是中国悠久历史的见证。它与天安门，兵马俑一起被世人视为中国的象征。长城欢迎您！',
    isdram: 'false'
  },
  {
    speaker: '精品发音人',
    scene: '',
    type: '/',
    domain: '',
    age: '成年女声',
    style: '知性女声',
    info: '成熟知性、亲切自然',
    code: 'x_xiaoyan',
    function: 'vcn.x_xiaoyan',
    name: '晓燕',
    text: '白皮书说，党的十八大以来，中国的核安全事业进入安全高效发展的新时期。在核安全观引领下，中国逐步构建起法律规范、行政监管、行业自律、技术保障、人才支撑、文化引领、社会参与、国际合作等为主体的核安全治理体系，核安全防线更加牢固。'
  },
  {
    age: '成年女声',
    scene: '民族语言场景',
    languages: '藏语',
    style: '藏语女声',
    info: '亲切自然、年轻朴实',
    code: 'sgron_dkar',
    function: 'vcn.sgron_dkar',
    name: '达娃',
    translation: '您好，欢迎使用科大讯飞语音合成系统，我是发音人卓玛',
    text: 'ཁྱེད་བདེ་མོ།  ཨན་ཧུའིཚན་རྩལ་སློབ་ཆེན་ཤུན་ཧྥེ་སྐད་གདངས་འདྲེས་སྦྱོར་བརྒྱུད་ཁུངས་བཀོལ་སྤྱོད་བྱེད་པར་དགའ་བསུ་བྱེད།  ང་ནི་སྒྲ་གཏོང་བ་སྒྲོལ་མ་ཡིན། ',
    language_type: '1'
  },
  {
    age: '成年女声',
    scene: '多语种场景',
    languages: '阿拉伯语',
    style: '阿拉伯女声',
    info: '亲切自然、年轻朴实',
    code: 'x2_mohamed',
    function: 'vcn.x2_mohamed',
    name: 'mohamed',
    translation: '您好，欢迎使用科大讯飞语音合成系统',
    text: ' مرحبا ، مرحبا بكم في نظام التوليف الصوتي',
    language_type: '1',
    isdram: 'false'
  },
  {
    speaker: '特色发音人',
    scene: '方言场景',
    type: '方言',
    domain: '方言场景',
    age: '成年女声',
    style: '香港粤语',
    info: '',
    code: 'x2_xiaoyue',
    function: 'vcn.x2_xiaoyue',
    name: '小月',
    text: '释义：人民币升值是指相对其他货币来说，人民币的购买力增强，主要表现在同样数量的人民币可以换取更多数量的外币。但是人民币升值是相对外国货币来说的，在国内市场无法显现，钱并没有变得更加值钱。',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '客服场景',
    type: '小说',
    domain: '有声文章、纪录片、专题宣传',
    age: '成年女声',
    style: '亲切女声',
    info: '温柔亲切、亲切自然',
    code: 'x_mengchun',
    function: 'vcn.x_mengchun',
    name: '小春',
    text: '在中国大陆和宝岛台湾之间，一片浩浩淼淼的水域，如繁星般洒落着千礁百岛，海阔潮涌，天风吹梦。这就是福建平潭。平潭岛上的人们生来与海为伴，世代搏击于风口浪尖。一方水土养一方人，特殊的环境，孕育了岛民刚毅、豪迈、执着、拼搏的海洋文化精神。正是凭借着这种敢于担当、不避艰险、勇于开拓的冲劲和豪情，这里的人们创造了许许多多商业奇迹，宏扬了海纳百川、四海为家、敢拼会赢的“闽商”特质。'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '广告',
    domain: '广告促销、课件文本',
    age: '成年男声',
    style: '活泼男声',
    info: '饱满活泼、亲切自然',
    code: 'x_xiaoguan',
    function: 'vcn.x_xiaoguan',
    name: '小光',
    text: '好消息，好消息！时尚女装，冲量销售了，爆款棉衣，时尚保暖衣，保暖裤，打底裤，皮裤全部特价，朋友们，停一停，看一看，总有一款适合您！家有万贯，也要精打细算，用买白菜的价钱，买高档的服装，买的值得，买的划算！走过路过，不要错过，快来瞧一瞧，看一看吧，送一份孝心给妈妈，送一份爱心给老婆，送一份情意给姐妹，寒冷的冬天送衣服就是送温暖，快快行动吧！'
  },
  {
    speaker: '精品发音人',
    scene: '',
    type: '/',
    domain: '',
    age: '成年女声',
    style: '甜美女声',
    info: '温柔甜美、亲切自然',
    code: 'x_xiaomeng',
    function: 'vcn.x_xiaomeng',
    name: '小梦',
    text: '白皮书说，党的十八大以来，中国的核安全事业进入安全高效发展的新时期。在核安全观引领下，中国逐步构建起法律规范、行政监管、行业自律、技术保障、人才支撑、文化引领、社会参与、国际合作等为主体的核安全治理体系，核安全防线更加牢固。'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '故事',
    domain: '有声文章',
    age: '成年女声',
    style: '亲切女声',
    info: '亲切自然、成熟温柔',
    code: 'x_xiaoqiao',
    function: 'vcn.x_xiaoqiao',
    name: '小乔',
    text: '东京也无非是这样。上野的樱花烂熳的时节，望去确也像绯红的轻云，但花下也缺不了成群结队的“清国留学生”的速成班，头顶上盘着大辫子，顶得学生制帽的顶上高高耸起，形成一座富士山。也有解散辫子，盘得平的，除下帽来，油光可鉴，宛如小姑娘的发髻一般，还要将脖子扭几扭。实在标致极了。'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '小说',
    domain: '交互场景',
    age: '成年女声',
    style: '甜美女声',
    info: '年轻时尚、亲切自然',
    code: 'x_xiaoqing',
    function: 'vcn.x_xiaoqing',
    name: '小倩',
    text: '正在为您查询合肥的天气情况。今天是2020年2月24日，合肥市今天多云，最低温度9摄氏度，最高温度15摄氏度，微风。'
  },
  {
    speaker: '特色发音人',
    scene: '客服场景',
    type: '客服',
    domain: '客服场景、交互场景',
    age: '成年女声',
    style: '温柔女声',
    info: '温柔甜美、亲切自然',
    code: 'x2_chunchun',
    function: 'vcn.x2_chunchun',
    name: '春春',
    text: '您好，欢迎来到科大讯飞。您好，请问有什么可以帮您？正在为您查询，请稍等。感谢您的来电，祝您生活愉快。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '交互',
    domain: '客服场景、交互场景',
    age: '成年女声',
    style: '温柔女声',
    info: '温柔甜美、年轻时尚、亲切自然',
    code: 'x_dangdang',
    function: 'vcn.x_dangdang',
    name: '当当',
    text: '您好，欢迎来到科大讯飞。您好，请问有什么可以帮您？正在为您查询，请稍等。感谢您的来电，祝您生活愉快。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '交互',
    domain: '客服场景、交互场景、阅读场景',
    age: '成年女声',
    style: '亲切女声',
    info: '亲切自然',
    code: 'x2_qianqian',
    function: 'vcn.x2_qianqian',
    name: '倩倩',
    text: '您好，欢迎来到科大讯飞。您好，请问有什么可以帮您？正在为您查询，请稍等。感谢您的来电，祝您生活愉快。',
    isdram: 'false',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '/',
    domain: '阅读场景',
    age: '成年男声',
    style: '磁性男声',
    info: '稳重磁性、亲切自然',
    code: 'x2_xiaozhong',
    function: 'vcn.x2_xiaozhong',
    name: '小忠',
    text: '白皮书说，党的十八大以来，中国的核安全事业进入安全高效发展的新时期。在核安全观引领下，中国逐步构建起法律规范、行政监管、行业自律、技术保障、人才支撑、文化引领、社会参与、国际合作等为主体的核安全治理体系，核安全防线更加牢固。',
    isdram: 'false',
    recommended: '新'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景',
    type: '广告',
    domain: '广告促销',
    age: '成年女声',
    style: '亲切女声',
    info: '激情洋溢、自然亲切、年轻时尚',
    code: 'x_chengcheng',
    function: 'vcn.x_chengcheng',
    name: '程程',
    text: '好消息，好消息！时尚女装，冲量销售了，爆款棉衣，时尚保暖衣，保暖裤，打底裤，皮裤全部特价，朋友们，停一停，看一看，总有一款适合您！家有万贯，也要精打细算，用买白菜的价钱，买高档的服装，买的值得，买的划算！走过路过，不要错过，快来瞧一瞧，看一看吧，送一份孝心给妈妈，送一份爱心给老婆，送一份情意给姐妹，寒冷的冬天送衣服就是送温暖，快快行动吧！',
    isdram: 'false'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '情感',
    domain: '儿童读物',
    age: '女童声',
    style: '甜美女童',
    info: '可爱甜美、委屈撒娇',
    code: 'x_mengmengSad',
    function: 'vcn.x_mengmengSad',
    name: '萌萌-悲伤',
    text: '布娃娃，别生气。布娃娃，你别生气，我来给你赔个礼。刚才不该发脾气，使劲把你扔在地。弄脏了你的新花衣，摔得你脸上都是泥。一定还很疼吧?真是对不起！衣服脏了我给你拍，脸儿脏了我给你洗，从今以后，我要爱护你。'
  },
  {
    speaker: '特色发音人',
    scene: '通用场景、阅读场景',
    type: '广告',
    domain: '广告促销、专题宣传、阅读场景、纪录片',
    age: '成年女声',
    style: '甜美女声',
    info: '年轻时尚、自然甜美',
    code: 'x_xiaoxue_daqi',
    function: 'vcn.x_xiaoxue_daqi',
    name: '小薛',
    text: '好消息，好消息！时尚女装，冲量销售了，爆款棉衣，时尚保暖衣，保暖裤，打底裤，皮裤全部特价，朋友们，停一停，看一看，总有一款适合您！家有万贯，也要精打细算，用买白菜的价钱，买高档的服装，买的值得，买的划算！走过路过，不要错过，快来瞧一瞧，看一看吧，送一份孝心给妈妈，送一份爱心给老婆，送一份情意给姐妹，寒冷的冬天送衣服就是送温暖，快快行动吧！',
    isdram: 'false'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '小说',
    domain: '有声文章、纪录片、专题宣传',
    age: '成年女声',
    style: '温柔女声',
    info: '温柔年轻、亲切自然',
    code: 'x2_xiaoai',
    function: 'vcn.x2_xiaoai_novel',
    name: '诺诺',
    text: '东京也无非是这样。上野的樱花烂熳的时节，望去确也像绯红的轻云，但花下也缺不了成群结队的“清国留学生”的速成班，头顶上盘着大辫子，顶得学生制帽的顶上高高耸起，形成一座富士山。也有解散辫子，盘得平的，除下帽来，油光可鉴，宛如小姑娘的发髻一般，还要将脖子扭几扭。实在标致极了。',
    recommended: '新升级'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '情感',
    domain: '儿童读物、有声文章',
    age: '女童声',
    style: '甜美女童',
    info: '可爱甜美、活泼愉悦',
    code: 'x_mengmengHappy',
    function: 'vcn.x_mengmengHappy',
    name: '萌萌-高兴',
    text: '布娃娃，别生气。布娃娃，你别生气，我来给你赔个礼。刚才不该发脾气，使劲把你扔在地。弄脏了你的新花衣，摔得你脸上都是泥。一定还很疼吧?真是对不起！衣服脏了我给你拍，脸儿脏了我给你洗，从今以后，我要爱护你。'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '小说',
    domain: '有声文章、纪录片、专题宣传',
    age: '成年女声',
    style: '亲切女声',
    info: '亲切自然、稳重知性',
    code: 'x_xiaonuo_novel',
    function: 'vcn.x_xiaonuo_novel',
    name: '小瑞',
    text: '东京也无非是这样。上野的樱花烂熳的时节，望去确也像绯红的轻云，但花下也缺不了成群结队的“清国留学生”的速成班，头顶上盘着大辫子，顶得学生制帽的顶上高高耸起，形成一座富士山。也有解散辫子，盘得平的，除下帽来，油光可鉴，宛如小姑娘的发髻一般，还要将脖子扭几扭。实在标致极了。'
  },
  {
    speaker: '特色发音人',
    scene: '阅读场景',
    type: '故事',
    domain: '儿童读物、纪录片、专题宣传',
    age: '成年男声',
    style: '活泼男声',
    info: '活泼轻快、年轻活力',
    code: 'x_xiaoyang_story',
    function: 'vcn.x_xiaoyang_story',
    name: '小华',
    text: '美丽的小白兔穿着漂亮的花裙子，哼着歌，蹦蹦跳跳地上了桥，它要到对面去采蘑菇。就在这时候，它看见对面的山羊伯伯也准备要过桥。小桥很窄，只能一个人过桥。小白兔看见了，停下脚步，大声说：“山羊伯伯您先过桥吧！”说完，它就从桥上退了下来。山羊伯伯过了桥，摸着小白兔的头夸奖道：“你真乖！”'
  },
  {
    speaker: '特色发音人',
    scene: '交互场景',
    type: '情感',
    domain: '儿童读物、有声文章',
    age: '女童声',
    style: '可爱女童',
    info: '可爱甜美、自然亲切',
    code: 'x_mengmengNeutral',
    function: 'vcn.x_mengmengNeutral',
    name: '萌萌-中立',
    text: '布娃娃，别生气。布娃娃，你别生气，我来给你赔个礼。刚才不该发脾气，使劲把你扔在地。弄脏了你的新花衣，摔得你脸上都是泥。一定还很疼吧?真是对不起！衣服脏了我给你拍，脸儿脏了我给你洗，从今以后，我要爱护你。'
  }
]
