export default [
  {
    bGM: false,
    baseModelId: 25,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '通用',
    sequence: 996,
    speaker: '艾琪',
    speakerId: 'aiqi',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aiqi',
    speechType: '温柔女声',
    tag: '',
    text: '哎呀，你要问我喜欢吃什么，我能答上一堆。问我不喜欢的啊，那我还真答不上来。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 28,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '通用',
    sequence: 994,
    speaker: '艾诚',
    speakerId: 'aicheng',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aicheng',
    speechType: '标准男声',
    tag: '',
    text: '信息革命、移动互联网革命尚未落幕，智能革命又像一头大象一样撞进人类的生活，激荡着整个世界。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 27,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '通用',
    sequence: 991,
    speaker: '艾佳',
    speakerId: 'aijia',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aijia',
    speechType: '标准女声',
    tag: '',
    text: '从目前来看，创业板显然并未受到严重的影响。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 9,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '通用',
    sequence: 990,
    speaker: '思琪',
    speakerId: 'siqi',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#siqi',
    speechType: '温柔女声',
    tag: '',
    text: '有人说，他性格外冷内热，更多的人认为他冷酷无情。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 10,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '通用',
    sequence: 980,
    speaker: '思佳',
    speakerId: 'sijia',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#sijia',
    speechType: '标准女声',
    tag: '',
    text: '尽管已年近七旬，但王时凯看起来依然精神矍铄。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 83,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '通用',
    sequence: 970,
    speaker: '马树',
    speakerId: 'mashu',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#mashu',
    speechType: '儿童剧男声',
    tag: '',
    text: '有一天，小主人又送来食物，小兔子迫不及待地跑过去挑黄豆和玉米吃。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 89,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '通用',
    sequence: 969,
    speaker: '悦儿',
    speakerId: 'yuer',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#yuer',
    speechType: '儿童剧女声',
    tag: '',
    text: '小兔子照猴子医生的话去做了，果然牙齿不疼了，身体也壮实了。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 3,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '通用',
    sequence: 960,
    speaker: '若兮',
    speakerId: 'ruoxi',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#ruoxi',
    speechType: '温柔女声',
    tag: '',
    text: '这一次交锋，双方都没有占到什么便宜，可以说是旗鼓相当。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 31,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '通用',
    sequence: 952,
    speaker: '艾达',
    speakerId: 'aida',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aida',
    speechType: '标准男声',
    tag: '',
    text: '乡村是中国的根脉，是国家大厦的基础，乡村治理具有极端重要性。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 11,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '通用',
    sequence: 951,
    speaker: '思诚',
    speakerId: 'sicheng',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#sicheng',
    speechType: '标准男声',
    tag: '',
    text: '在全市形成了上下联动、共同推进的良好氛围。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 15,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '通用',
    sequence: 950,
    speaker: '宁儿',
    speakerId: 'ninger',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#ninger',
    speechType: '标准女声',
    tag: '',
    text: '随着量能的放大、涨停股的增多，市场被调动起来。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 1,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '通用',
    sequence: 920,
    speaker: '小云',
    speakerId: 'xiaoyun',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#xiaoyun',
    speechType: '标准女声',
    tag: '',
    text: '广袤的辽北大地，处处萌发盎然春意。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 2,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '通用',
    sequence: 910,
    speaker: '小刚',
    speakerId: 'xiaogang',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#xiaogang',
    speechType: '标准男声',
    tag: '',
    text: '当天，北京飞往上海虹桥的航班也因天气原因导致延误。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 33,
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '客服',
    sequence: 895,
    speaker: '艾夏',
    speakerId: 'aixia',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aixia',
    speechType: '亲和女声',
    tag: '',
    text: '为了减少您的损失，请您今天晚上6点前尽快处理好本次欠款，好吧？',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 24,
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '客服',
    sequence: 894,
    speaker: '艾悦',
    speakerId: 'aiyue',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aiyue',
    speechType: '温柔女声',
    tag: '',
    text: '好的，王先生，最后温馨提醒您，我银行将在您申请财智金成功批核后，为您发送《财智金产品服务协议》及资金用途管控要求的短信，请您注意查阅。那先不打扰您了，祝您用卡愉快，谢谢您的接听，再见。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 38,
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '客服',
    sequence: 893,
    speaker: '艾雅',
    speakerId: 'aiya',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aiya',
    speechType: '严厉女声',
    tag: '',
    text: '是这样子的，张欢女士，现在您的信用卡，因为逾期31天以上，已经被冻结停卡。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 35,
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '客服',
    sequence: 892,
    speaker: '艾婧',
    speakerId: 'aijing',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aijing',
    speechType: '严厉女声',
    tag: '',
    text: '如果您在今天下午六点之前仍未进行处理，将会产生更多不必要的费用，并且会影响您的信用记录。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 26,
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '客服',
    sequence: 891,
    speaker: '艾美',
    speakerId: 'aimei',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aimei',
    speechType: '甜美女声',
    tag: '',
    text: '您好，我这边是XY证券的，您开户的证券公司，请问是李万峰先生吗？想和您做个简单的回访，可以吗？',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 12,
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '客服',
    sequence: 890,
    speaker: '思悦',
    speakerId: 'siyue',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#siyue',
    speechType: '温柔女声',
    tag: '',
    text: '张先生您好，您本月VPN流量已使用百分之八十，您还可以查询四月及近五个月的账单。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 44,
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '客服',
    sequence: 889,
    speaker: '艾娜',
    speakerId: 'Aina',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#Aina',
    speechType: '浙普女声',
    tag: '',
    text: '现在需要和您确认，当前接听的这部手机是否是在1个月内购买的。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 58,
    img: 'https://img.alicdn.com/tfs/TB1VmzHbjMZ7e4jSZFOXXX7epXa-238-238.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '客服',
    sequence: 886,
    speaker: '艾硕',
    speakerId: 'aishuo',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aishuo',
    speechType: '自然男声',
    tag: '',
    text: '您好刘晓梅女士，请您在明天零点前，确保卡内金额至少为八百九十七元九毛钱。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 32,
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '客服',
    sequence: 885,
    speaker: '艾雨',
    speakerId: 'aiyu',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aiyu',
    speechType: '自然女声',
    tag: '',
    text: '这项手机保障权益只针对新购买1个月内的手机有效，置换费需要125元。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 13,
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '客服',
    sequence: 880,
    speaker: '小美',
    speakerId: 'xiaomei',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#xiaomei',
    speechType: '甜美女声',
    tag: '',
    text: '齐先生，您的支付宝绑定的是18912345678这个手机号吗？',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 17,
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '客服',
    sequence: 870,
    speaker: '伊娜',
    speakerId: 'yina',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#yina',
    speechType: '浙普女声',
    tag: '',
    text: '尊敬的王大志先生，我是智能数码专营店的售后客服，请问有什么可以帮您？',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 18,
    img: 'https://img.alicdn.com/tfs/TB1w8u6DSzqK1RjSZFpXXakSXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '客服',
    sequence: 865,
    speaker: '思婧',
    speakerId: 'sijing',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#sijing',
    speechType: '严厉女声',
    tag: '',
    text: '您的欠款98789.1元，在5月1号即将到还款日期，请您尽快还款，谢谢。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 48,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 785,
    speaker: '艾媛',
    speakerId: 'aiyuan',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#9c1d686301e90bc4a2d2dd28b78275bc',
    speechType: '知心姐姐',
    tag: '精品',
    text: '新鲜的微风吹动我的衣袂，如同爱人的鼻息吹着我的手一样。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 68,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 784,
    speaker: '艾厨',
    speakerId: 'aichu',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#e72f24f46dd140db96997aeba0b2b76b',
    speechType: '舌尖男声',
    tag: '精品',
    text: '撇净筒内浮沫，再放入洗净的原料和干贝，静等一锅美味的羹汤慢慢熬制。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 69,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 783,
    speaker: '艾倩',
    speakerId: 'aiqian',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#627997f949bcdcb5d69a5d4afd4f80a2',
    speechType: '资讯女声',
    tag: '精品',
    text: '在敬茶时除了论资排辈，按部就班之外，还得先敬客人来宾，然后再敬自家人。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 63,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 782,
    speaker: '艾楠',
    speakerId: 'ainan',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#23889292333b3cad9ac5f8ae846d88e9',
    speechType: '广告男声',
    tag: '精品',
    text: '图案采用条纹设计，简洁印花，更加可爱童趣。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 66,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 781,
    speaker: '艾笑',
    speakerId: 'aixiao',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#6257d57f725a002b6f1a9bf8dab067f9',
    speechType: '资讯女声',
    tag: '精品',
    text: '很多超市，自制食品俨然已经成为主打产品。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 49,
    img: 'https://img.alicdn.com/tfs/TB1WCzHbjMZ7e4jSZFOXXX7epXa-238-238.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 780,
    speaker: '艾颖',
    speakerId: 'aiying',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#5b6da13155adc6de61a80e3f9f893e4c',
    speechType: '软萌童声',
    tag: '精品',
    text: '小蚂蚁扛着沉重的饭粒跑了半天，累得他浑身冒汗。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 50,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 770,
    speaker: '艾祥',
    speakerId: 'aixiang',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#acbd71e3d8edd6ccd57a0522fba6c229',
    speechType: '磁性男声',
    tag: '精品',
    text: '他望着渐行渐远的马车叹了口气，一转身，便消失在云雾当中。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 64,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 769,
    speaker: '艾浩',
    speakerId: 'aihao',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#9bdb75cd7de9cb67d78fa661a33cc183',
    speechType: '资讯男声',
    tag: '精品',
    text: '一旦入驻，这一板块的价格势必迅速高涨。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 51,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 768,
    speaker: '艾墨',
    speakerId: 'aimo',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#c2f2fcd8f567a02a85297d5c5db1040a',
    speechType: '情感男声',
    tag: '精品',
    text: '爹爹放心，我和大哥平日无事，便会去照顾他的。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 65,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 767,
    speaker: '艾茗',
    speakerId: 'aiming',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#33868851ec92105e001dfca60c011152',
    speechType: '诙谐男声',
    tag: '精品',
    text: '在二战期间，布劳格加入杜邦公司进行科研工作。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 52,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 766,
    speaker: '艾晔',
    speakerId: 'aiye',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#0fb512e88aa09784729f2f6b2883a0a6',
    speechType: '青年男声',
    tag: '精品',
    text: '山顶上站着一位青年，剑眉钩鼻，一袭白衣，腰间有一柄青石宝剑。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 59,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 765,
    speaker: '艾德',
    speakerId: 'aide',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#87a4f89dbcdda862656068534d7005a9',
    speechType: '新闻男声',
    tag: '精品',
    text: '民航局共执行国际包机178架次，运送抗疫物资1635吨',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 72,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 764,
    speaker: '艾树',
    speakerId: 'aishu',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#54f9d35ec1a930540c4dbf49fa12201e',
    speechType: '资讯男声',
    tag: '精品',
    text: '我开始有很多感慨，但感慨终究也只是感慨。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 73,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 763,
    speaker: '艾茹',
    speakerId: 'airu',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#5545c92757ee771946fa935ab6352238',
    speechType: '新闻女声',
    tag: '精品',
    text: '大家一致认为：他亲临湖南考察，发表重要讲话，充分体现了对湖南工作的高度重视',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 53,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 760,
    speaker: '艾婷',
    speakerId: 'aiting',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#a309a9d93254ccfc26b8be237bdd777b',
    speechType: '电台女声',
    tag: '精品',
    text: '请你来的时候，带一朵微启的玫瑰，我将久久的，久久的轻嗅，这人世间不变的香痕。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 54,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '文学',
    sequence: 750,
    speaker: '艾凡',
    speakerId: 'aifan',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#545cbcae86c79db5e8380b4b8eeef356',
    speechType: '情感女声',
    tag: '精品',
    text: '黑匣子里薛定谔的猫要么是死要么是活，与你是否打开黑匣子无关。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 91,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '超高清',
    sequence: 682,
    speaker: '知祥',
    speakerId: 'zhixiang',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#c051cb1b4e836bad21cb176701ee4881',
    speechType: '磁性男声',
    tag: '精品',
    text: '不久，法医便发现，死者的脚部有红豆大小的疤痕。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 84,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '超高清',
    sequence: 680,
    speaker: '知琪',
    speakerId: 'zhiqi',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#14a095fde68d70d7e096cbf8094e3d94',
    speechType: '温柔女声',
    tag: '精品',
    text: '春日阳光普照大地，正是踏春好时节。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 94,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '超高清',
    sequence: 678,
    speaker: '知倩',
    speakerId: 'zhiqian',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#216b6683b02d783b1a4d0f00a6173aa6',
    speechType: '资讯女声',
    tag: '精品',
    text: '抄袭的背后是两家屡次产品雷同，同质化严重。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 93,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '超高清',
    sequence: 675,
    speaker: '知楠',
    speakerId: 'zhinan',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#1da71044ddbe4fc9ba17a34ee9d0a103',
    speechType: '广告男声',
    tag: '精品',
    text: '修身的版型剪裁，线条顺滑流畅，给人愉悦的视觉感受。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 85,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '超高清',
    sequence: 670,
    speaker: '知厨',
    speakerId: 'zhichu',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#15e5877e97914e4f1eb08b293dea0e69',
    speechType: '舌尖男声',
    tag: '精品',
    text: '这是一年中最美味的团聚，也注定是一顿百感交集的晚餐。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 96,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '超高清',
    sequence: 665,
    speaker: '知德',
    speakerId: 'zhide',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#c599498946462472d62fcf3a10eb8da7',
    speechType: '新闻男声',
    tag: '精品',
    text: '经历了职业生涯的这次季后赛，他也品尝到其中的苦涩和遗憾。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 95,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '超高清',
    sequence: 660,
    speaker: '知茹',
    speakerId: 'zhiru',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#9cbc04390cf7eed449ea3319fdb35b8b',
    speechType: '新闻女声',
    tag: '精品',
    text: '科技产品面对面系列活动启动，为创新企业，提供个性化服务。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 92,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '超高清',
    sequence: 650,
    speaker: '知佳',
    speakerId: 'zhijia',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#0e33ee0e1a1fa0fc050830bfdd5cb1fb',
    speechType: '标准女声',
    tag: '精品',
    text: '市民在北京奥林匹克公园，乐享周末休闲时光。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 88,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '直播',
    sequence: 585,
    speaker: '小仙',
    speakerId: 'xiaoxian',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#xiaoxian',
    speechType: '亲切女声',
    tag: '',
    text: '放心吧，我们家羽绒服做的非常好，很保暖，主播这点还是很有自信的。37号链接，上链接了哈！',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 77,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '直播',
    sequence: 582,
    speaker: '柜姐',
    speakerId: 'guijie',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#guijie',
    speechType: '亲切女声',
    tag: '',
    text: '欢迎进来的宝宝，没关注主播的，去关注一下主播噢。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 78,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '直播',
    sequence: 580,
    speaker: 'Stella',
    speakerId: 'stella',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#stella',
    speechType: '知性女声',
    tag: '',
    text: '宝宝们，下面给大家推荐下，我们的这款电动牙刷。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 90,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '直播',
    sequence: 578,
    speaker: '猫小美',
    speakerId: 'maoxiaomei',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#maoxiaomei',
    speechType: '活力女声',
    tag: '',
    text: '我们这款电饭煲可是非常畅销的宝贝，心动的宝宝们，赶紧下单呀。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 79,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '直播',
    sequence: 575,
    speaker: 'Stanley',
    speakerId: 'stanley',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#stanley',
    speechType: '沉稳男声',
    tag: '',
    text: '冬季是最能演绎叠穿的季节，只要你够大胆，时髦的造型，随时都能拥有。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 80,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '直播',
    sequence: 574,
    speaker: 'Kenny',
    speakerId: 'kenny',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#kenny',
    speechType: '温暖男声',
    tag: '',
    text: '现在大家看到的这件宝贝，可以预约保温，迷你小巧，能够均匀加热，美观大气。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 81,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '直播',
    sequence: 573,
    speaker: 'Rosa',
    speakerId: 'rosa',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#rosa',
    speechType: '自然女声',
    tag: '',
    text: '亲爱的宝宝们，大家好，给大家推荐一款迪士尼女童内衣套装',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 29,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '通用',
    sequence: 545,
    speaker: '瑞琳',
    speakerId: 'ruilin',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#ruilin',
    speechType: '标准女声',
    tag: '',
    text: '中国传统文化讲究节日团圆，到了春节，就更期待一家人聚在一起热热闹闹的吃饭啦。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 36,
    img: 'https://img.alicdn.com/tfs/TB1NW9ZDMDqK1RjSZSyXXaxEVXa-516-516.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '童声',
    sequence: 493,
    speaker: '艾彤',
    speakerId: 'aitong',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aitong',
    speechType: '儿童音',
    tag: '',
    text: '春秋时，宋国有一位农夫，他正在田里工作的时候，突然看见一只兔子往大树的方向快跑。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 37,
    img: 'https://img.alicdn.com/tfs/TB1NW9ZDMDqK1RjSZSyXXaxEVXa-516-516.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '童声',
    sequence: 492,
    speaker: '艾薇',
    speakerId: 'aiwei',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aiwei',
    speechType: '萝莉女声',
    tag: '',
    text: '老虎你别急，听我说。我是上帝派来做百兽之王的！你要是吃了我，那就是违背了上帝的命令！',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 34,
    img: 'https://img.alicdn.com/tfs/TB1NW9ZDMDqK1RjSZSyXXaxEVXa-516-516.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '童声',
    sequence: 491,
    speaker: '艾宝',
    speakerId: 'aibao',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#aibao',
    speechType: '萝莉女声',
    tag: '',
    text: '又见面啦，试试对我说“我要听小猪佩奇”。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 16,
    img: 'https://img.alicdn.com/tfs/TB1NW9ZDMDqK1RjSZSyXXaxEVXa-516-516.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '童声',
    sequence: 490,
    speaker: '小北',
    speakerId: 'xiaobei',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#xiaobei',
    speechType: '萝莉女声',
    tag: '',
    text: '这个家伙还是一如既往的蛮横不讲理。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 14,
    img: 'https://img.alicdn.com/tfs/TB1NW9ZDMDqK1RjSZSyXXaxEVXa-516-516.png',
    language: '中文普通话',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '童声',
    sequence: 480,
    speaker: '思彤',
    speakerId: 'sitong',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#sitong',
    speechType: '儿童音',
    tag: '',
    text: '孩子还不知道忧愁，白白胖胖的很可爱。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 42,
    img: 'https://img.alicdn.com/tfs/TB1Qa9ZDMDqK1RjSZSyXXaxEVXa-517-517.png',
    language: '英式英语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '英文',
    sequence: 396,
    speaker: 'Luca',
    speakerId: 'Luca',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#Luca',
    speechType: '英音男声',
    tag: '',
    text: 'Many lessons are boring, and he is very tired after doing gym.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 41,
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    language: '英式英语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '英文',
    sequence: 395,
    speaker: 'Luna',
    speakerId: 'Luna',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#Luna',
    speechType: '英音女声',
    tag: '',
    text: 'George is at the pet store, looking at what kind of pet he might want to get for his birthday.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 40,
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    language: '英式英语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '英文',
    sequence: 394,
    speaker: 'Emily',
    speakerId: 'Emily',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#Emily',
    speechType: '英音女声',
    tag: '',
    text: 'Saturday is better for me because I am meeting my parents on Sunday.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 39,
    img: 'https://img.alicdn.com/tfs/TB1Qa9ZDMDqK1RjSZSyXXaxEVXa-517-517.png',
    language: '英式英语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '英文',
    sequence: 393,
    speaker: 'Eric',
    speakerId: 'Eric',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#Eric',
    speechType: '英音男声',
    tag: '',
    text: 'Its case and internal components are made entirely from recycled, organic materials.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 30,
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    language: '英式英语',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '英文',
    sequence: 392,
    speaker: 'Olivia',
    speakerId: 'Olivia',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#Olivia',
    speechType: '英音女声',
    tag: '',
    text: 'MR Li, The amount of your current bill is 2050 yuan ,which needs to be paid before april twenty-one.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 46,
    img: 'https://img.alicdn.com/tfs/TB1Qa9ZDMDqK1RjSZSyXXaxEVXa-517-517.png',
    language: '美式英语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '英文',
    sequence: 392,
    speaker: 'Andy',
    speakerId: 'Andy',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#Andy',
    speechType: '美音男声',
    tag: '',
    text: 'View the latest news and breaking news today.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 45,
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    language: '美式英语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '英文',
    sequence: 391,
    speaker: 'Abby',
    speakerId: 'Abby',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#Abby',
    speechType: '美音女声',
    tag: '',
    text: 'We need to bring in an expert to deal with this problem.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 19,
    img: 'https://img.alicdn.com/tfs/TB1Qa9ZDMDqK1RjSZSyXXaxEVXa-517-517.png',
    language: '英式英语',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '英文',
    sequence: 390,
    speaker: 'William',
    speakerId: 'William',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#William',
    speechType: '英音男声',
    tag: '',
    text: 'Plans are already under way to start work on the project.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 57,
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    language: '英式英语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '英文',
    sequence: 390,
    speaker: 'Lydia',
    speakerId: 'Lydia',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#Lydia',
    speechType: '英中双语',
    tag: '',
    text: '大家好，我是来自英国的Lydia，我的中文说得还不错吧？',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 71,
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    language: '美式英语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '英文',
    sequence: 388,
    speaker: 'Annie',
    speakerId: 'annie',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#annie',
    speechType: '美语女声',
    tag: '',
    text: 'After my flight, we used to see quite often.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 20,
    img: 'https://img.alicdn.com/tfs/TB1lqGYDRLoK1RjSZFuXXXn0XXa-517-517.png',
    language: '英式英语',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '英文',
    sequence: 380,
    speaker: 'Wendy',
    speakerId: 'Wendy',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#Wendy',
    speechType: '英音女声',
    tag: '',
    text: 'Great, I hope you enjoy your dinner.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 74,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '粤语方言',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '方言',
    sequence: 290,
    speaker: '佳佳',
    speakerId: 'jiajia',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#jiajia',
    speechType: '粤语女声',
    tag: '',
    text: '超低折扣，限时购买，活动期间每个账号仅可购买一次，千祈唔好错过。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 76,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '粤语方言',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '方言',
    sequence: 285,
    speaker: '桃子',
    speakerId: 'taozi',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#taozi',
    speechType: '粤语女声',
    tag: '',
    text: '我五点再联系你, 廿分钟之后再见',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 22,
    img: 'https://img.alicdn.com/tfs/TB1Qa9ZDMDqK1RjSZSyXXaxEVXa-517-517.png',
    language: '英式英语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '英文',
    sequence: 260,
    speaker: 'Harry',
    speakerId: 'Harry',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#Harry',
    speechType: '英音男声',
    tag: '',
    text: 'Some of the provisions for the protection of minors have been included in the common position but not enough of them.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 62,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '台湾方言',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '方言',
    sequence: 250,
    speaker: '青青',
    speakerId: 'qingqing',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#qingqing',
    speechType: '台湾话女声',
    tag: '',
    text: '小主人，我是您的智能小助手，有问题请吩咐我吧！',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 61,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '东北女声',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '方言',
    sequence: 245,
    speaker: '翠姐',
    speakerId: 'cuijie',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#cuijie',
    speechType: '东北话女声',
    tag: '',
    text: '在俺们东北，有一种解决，叫“咋整”',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 60,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '湖南男声',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '方言',
    sequence: 230,
    speaker: '小泽',
    speakerId: 'xiaoze',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#xiaoze',
    speechType: '湖南重口音',
    tag: '',
    text: '早上好，今天长沙多云转晴，10度到17度，空气质量良。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 23,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '粤语方言',
    pitchRate: 0,
    sampleRate: 24000,
    scene: '方言',
    sequence: 210,
    speaker: '姗姗',
    speakerId: 'shanshan',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#shanshan',
    speechType: '粤语女声',
    tag: '',
    text: '当前客服繁忙，为免耽误您的时间，您可以尝试通过支付宝HK APP里面【客户服务】查询您嘅问题。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 67,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '日语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '多语种',
    sequence: 180,
    speaker: '智香',
    speakerId: 'tomoka',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#tomoka',
    speechType: '日语女声',
    tag: '',
    text: 'ぐっすり眠った後は、ずっと気分がよい。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 70,
    img: 'https://img.alicdn.com/tfs/TB1Ek54DPTpK1RjSZKPXXa3UpXa-517-517.png',
    language: '日语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '多语种',
    sequence: 175,
    speaker: '智也',
    speakerId: 'tomoya',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#tomoya',
    speechType: '日语男声',
    tag: '',
    text: 'にやりと笑って、賛成の意思を示した。',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 75,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '印尼语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '多语种',
    sequence: 170,
    speaker: 'Indah',
    speakerId: 'indah',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#indah',
    speechType: '印尼女声',
    tag: '',
    text: 'Dia memulai perjalanan yang akan mengubah jalan hidupnya.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 82,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '马来语',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '多语种',
    sequence: 168,
    speaker: 'Farah',
    speakerId: 'farah',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#farah',
    speechType: '马来语女声',
    tag: '',
    text: 'Proses keadilan hendaklah berlaku terhadap semua pihak dan tidak seharusnya wujud pilih kasih.',
    volume: 0
  },
  {
    bGM: false,
    baseModelId: 56,
    img: 'https://img.alicdn.com/tfs/TB1Ij98DQPoK1RjSZKbXXX1IXXa-517-517.png',
    language: '四川方言',
    pitchRate: 0,
    sampleRate: 16000,
    scene: '方言',
    sequence: 9,
    speaker: '小玥',
    speakerId: 'xiaoyue',
    speechFrom: '官方',
    speechRate: 0,
    speechTtsModelKey: '88#xiaoyue',
    speechType: '四川话女声',
    tag: '',
    text: '现在给你放起，《黑猫警长》第八集《谁是凶手》。',
    volume: 0
  }
];
